language: python            # this works for Linux but is an error on macOS or Windows
sudo: required
cache: pip

env:
  global:
    # GITHUB_TOKEN
    - secure: "scbwc6CuiVf7ryKROBNOdbRAr2RyF/rcquGYL5Gsf3CMXukGyT95NNP8KwZLH/MSWg5I9wItb9b0lMxqad3sz28jbr7ARKooC5vfT3A2m5aMN8Y+7QoG3myYirsOjpwDW9zjk7/vjGT1QZh1twr6fg10pLPfZWAGxAbKLTVzcDsvhPu9+9uzvkrZitPc1EhUmjhusF2dnSKqBjYE/dYrz/xHwNGKYSlqkl+CBVBi6T7LC3J6LHUFKNo0QfqkW0EW6hATAWeLXgu9pT917B6BPpwll2oAZT5J9oFbms/szAelzsWBAJedyEIkJ4EzPlk9qokOr61kWFZ+7hkAXfj+Mq7k4VQXorFPWub0sZ+nMtfbAoZ6PO+REpH9BLBQGFwvwpHlp5DvKh+XHtIxFnmm107+AS7vNI94bSbObWDuzbcrwiKZUXNkExjaGQtLI/RV2XeDXIYr6T6SPYW+Ayr7Uutmqv1oUkdqEt1yCxNpsWly09teTac7ZnxgWqewcvr9ayLRC/l9ffAP5PHCErMm67pv8bXEiTRuMzbNTgHxbKOEqtSoEgI1xoU/+J2r+bO6sJs8QzKPNKfQWKyZRu/+KPOkZmKt9yzBQe57frDoEgCaBMGYwFyUyrqBaWKi4xSwcKYfeT3mexQ6pvemfp7+umFU/HAVkHxYLm6MXnu584E="
    # CODE_SIGN_PSWD_DICT
    - secure: "MUGB3OUDTpB8ZN70aRBmsCEqeUXsxMgNR5aDrTzgaOR8UIrAhRs30GH8NnASe8VIO6L48SRqGoFeXA4ZZ9h8RFZxQBcPG88/bKzPvPni+WQC5QYF9zbK1mv5IzHfurK08eH05FVz9Mx1BA/L0gviwnP4S4+1ICou0EnnO+sxxGFcGw+ixUpDYPJ2A+R6Dz5OICd2yUVGj3tD2ZYUY+dfnWbTtysb29OMbSMLIMybJ0MOXJ1ozWJibWmyV1tqo4eJ6ZeZKEhH4vKnWtZAeZ6MHLzWLN++jAc3XqxZAJ2czMpsHMeGRx3rjnyGqTXoVFPdmDovRmFZdF7RLYOVWiOKqpc041OMouy2E/dEZ48qJTqkFWQnLqu5HTQCx98RAwIh2czJni0N9DAViv0W/Vj+20JL03hIKYDWXBbigPKFQMI04DobYakBGB/NR3iWhTU4jpG84ttWmtkRfvmPBgIP5zxpJf6xUK6IK02zlENVyzX/X4gZ0cNwGMA7qUpPeBKAVVf8XVf5rSrTPKmH87K1TTbuKn4yP/nx9XqpEcTbkF+LkoyAeCyPEwds3sG9he1uXUd9N+kK/tBC+g444bfHmPJy+6qLS3UK/egX1mweYNVZ6ljA5Aoy4kYlNOJc7XVamjF6aQtBx2yADx5jZJkIhK29Rfy28br4sMaaIDyOysM="

matrix:
  include:
    # Linux
    - name: "Python 3.7.1 on Ubuntu Linux 16.04 (Xenial)"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      dist: xenial
      env: BADGE=linux
    # macOS
    - name: "Python 3.7.0 on macOS 10.13 (High Sierra)"
      os: osx
      osx_image: xcode9.4   # osx_image: xcode11 --- Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 -m venv $TRAVIS_BUILD_DIR/.python-venv # create virtual environment for convenience
        - source $TRAVIS_BUILD_DIR/.python-venv/bin/activate # activate virtual environment
      env: BADGE=osx
    # Windows
    - name: "Python 3.7.0 on Windows 10.0"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      filter_secrets: false
      before_install:
        - choco install python --version=3.7.0 # 3.8 fails with cryspy
        - pip install pypiwin32
      env:
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - BADGE=win

install:
  - python --version
  #
  - python -m pip install --upgrade pip
  - pip --version
  #
  - pip install cryspy==0.1.13
  - pip install PySide2==5.13.1
  - pip install pyinstaller==3.5
  - pip install requests==2.22.0
  - pip install uritemplate==3.0.0
  - pip install pyyaml==5.1.2
  #
  - pip install pytest
  - pytest --version
  #
  - pip install pytest_mock
  - pip install pytest-cov
  - pip install pytest-qt
  #
  - pip install codecov

before_script:
  #- export RELEASE_NUMBER=`python Scripts/GetReleaseNumber.py`
  #- export TRAVIS_TAG=`python Scripts/GetTravisTag.py $RELEASE_NUMBER $TRAVIS_BRANCH`
  #- export RELEASE_TITLE=easyDiffraction-$TRAVIS_TAG
  - echo $TRAVIS_OS_NAME
  - echo $TRAVIS_BRANCH
  #- echo $RELEASE_NUMBER
  #- echo $TRAVIS_TAG
  #- echo $RELEASE_TITLE
  #- python Scripts/CompilePyResource.py
  - python Scripts/PrintLog.py
  - python Scripts/CreateProjectConfig.py

script:
  # Compile qrc (qt resource file) into python file
  #- pyside2-rcc App/QmlResource.qrc -o App/QmlResource.py -no-compress
  - python Scripts/CopyMissingLibs.py
  - python Scripts/MakeDist.py
  - python Scripts/MakeInstaller.py
  - python Scripts/SignCode.py $CODE_SIGN_PSWD_DICT
  - python Scripts/MakeArchive.py #$RELEASE_NUMBER
  - if [ "$TRAVIS_OS_NAME" == osx ]; then export PYTHONPATH=.:App:App/PyImports:$PYTHONPATH; pytest --cov=App Tests; fi
  - if [ "$TRAVIS_OS_NAME" != osx ]; then python runTests.py; fi
  - python Scripts/UploadArtifacts.py #$GITHUB_TOKEN

after_success:
  - codecov

#cache:
#  directories:
#    - ~/easyDiffraction

#before_deploy:
#  # Set up git user name and tag this commit
#  - git config --local user.name "Travis CI"
#  - git config --local user.email "travis@travis-ci.org"
#  # This writes a changelog. If wanted
#  #- '[ "$TRAVIS_BRANCH" != master ] || cd ../ && pip3 install gitchangelog pystache && echo "output_engine = mustache(\"markdown\")" > .gitchangelog.rc && gitchangelog ^$(git describe --abbrev=0 --tags) HEAD > CHANGELOG'

#deploy:
#  provider: script
#  script: python Scripts/UploadArtifacts.py #$GITHUB_TOKEN
#  skip_cleanup: true
#  on:
#    all_branches: true

#  - provider: releases # GitHub repository
#    name: $RELEASE_TITLE
#    api_key:
#      secure: "s3uqRW5prwmZp8dFSroXQCUBOFOCVU10iSGMVfBCtn51HDmF/RXDlQw7UJHs8vJJbtY+0tQ2yByCj5nah6VzaXKVyvxl7/VXGgB67LkHaI4idKV8HOqcSShJ1sxGapvMC3u5Ezx8tg3cK09SJnSFXq/xk9NoTdmxuFDX6X9P3jRq/CKM5mkHkOiUWLeU86sulJiBIBdcYoFwIXOKQE5KlDDBFDiI/qnEC98B4lKMSzRQB5VQEXeW+Z4f7KsK7/aS8H+Tw0sA+P81TN8CVXBeWAhBpEzrSAxLGEMRTP5GY/AkiJbdBuJMmHcc1t0S79OBsKQcrV2Yl9CtN4/WuvIH2caX19z39AvfjzDyHMnkDzN0XBv5fvQYla/45PxdmQf8O6GaiITXewBu+1DT9nQzLLaLh6GHz/zdGZeO2/ivwBMQnd8A3+B8YaO5/2dYGndAPDt06ECQBKI6RGvEBfTjApSTnuX07CjAwkXyg39uZo4KRtF1FGSjZdcNaDQGByPNHu4IOM60xDgM7VHI0EBz5YfZMpVs0sVTIsnwe7m+tFzRa00E/mlFdPCUvpYeZxgBJpNIvoBA53R7hUcvPd/xNeTfiT7tF08cAc3rdm+Mmdeewifn91SGunUBwLiNBVLB6YVlIfj2Btkce5fgdLTkVGnBlnawGAZtJwtH1Z6EJR4="
#    skip_cleanup: true
#    draft: true
#    overwrite: true
#    file_glob: true
#    file: easyDiffraction-*.zip
#    on:
#      all_branches: true

#after_deploy:
#  -  |
#     if [ $TRAVIS_BRANCH = "master" ]; then
#        cd ~/
#        git clone https://github.com/easyDiffraction/easyDiffraction.github.io.git
#        cd easyDiffraction.github.io
#        git remote set-url origin https://$GH_TOKEN@github.com/easyDiffraction/easyDiffraction.github.io.git
#        cat index_template.html | awk '{gsub(/RELEASE_V/,"'$TRAVIS_TAG'")}1' | awk '{gsub(/RELEASE_N/,"'$RELEASE_NUMBER'")}1' | awk '{gsub(/RELEASE_D/,"'$(date +'%d %b %Y')'")}1' > index.html
#        git add index.html
#        git commit -m 'Bumped release links [ci skip]'
#        git push origin HEAD:master
#     fi

notifications:
  slack:
    rooms:
      - secure: "t0nR618a2fr2EDpyfKWBBkcf5MJ549P732EGvN9gwXVYvl4z977KSSH6uPEw7/KmMec9BhMg882hJidoeh1XgvUQOiVan4jrlvn16z2INPWh/dloXOZN5YWz87tSLR1jn1tDaKSK7gaOF5HAosPbQ2/UriUaAG9d9GHJKJzCogNDAFwFge3K/b4KJr1kYpwS5Vd5K99peWnsrNYBz1M4+Xjc49cd5t5FKULtFduX0Zb25t3dQ25u9LfGQ5lyH65UNSqcu9DP4RZmX00KLYNnIOYtzuyWvehPhisoBozA+Fpuly2IaFPVswtHqO/h9kziyYBBcnEAvG0U+KHmkJy21vDHN5+yPoHlcuAr0Q95C7GEpUT/JVAeNggxWWF4WLYrcTbZXWGt69pBhuFUAZRnbzSV+wBF5ZAOK/5W9TvxYMM1uS9AqdLEmUQdtIGrj2VIDS1na0dielNMnOhBc0Xgap2as/Kb1aEkPuSA6kENDOGXrw1Vs0VjFK3iWOlyzHbfHdHWM1/WZOO2sZRNjdTgWS5x5UXJbozTcM5mzcAkZ21vVpVG5h7LQI3cMPpD45Hmtmnko6S+7FlaknesIeXXhZPwILxN12LtbBo7AkUqtdi/w4Do7CAA++hNJRQx2txa9Mfi6R9XhNccc9+3Mto6lw5hW9mDmb2b1TlrLksW5Ew="
    on_success: always
    on_failure: always

#https://docs.travis-ci.com/user/job-lifecycle/
