language: python            # this works for Linux but is an error on macOS or Windows
sudo: required
cache: pip

matrix:
  include:
    # Linux
    - name: "Python 3.7.1 on Ubuntu Linux 16.04 (Xenial)"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      dist: xenial
      env: BADGE=linux
    # macOS
    - name: "Python 3.7.0 on macOS 10.13 (High Sierra)"
      os: osx
      osx_image: xcode9.4   # osx_image: xcode11 --- Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 -m venv $TRAVIS_BUILD_DIR/.python-venv # create virtual environment for convenience
        - source $TRAVIS_BUILD_DIR/.python-venv/bin/activate # activate virtual environment
      env: BADGE=osx
    # Windows
    - name: "Python 3.7.4 on Windows 10.0"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      filter_secrets: false
      ###before_install:
        ###- choco install python --version=3.7.4 # 3.8 fails with cryspy
        ###- choco install zip
        ###- choco install curl
        ###- choco install grep
        ###- choco install sed
        ###- pip install pypiwin32
      env:
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - BADGE=win

env:
  global:
    - secure: "iUDKM5LbuZIrxqYewO4g8GKbpCvdIwbQckYVX9tj9pP9outFNzLicu7gGpL3gSkl52kzWQk8wtsE27Yx4EYE4i5N6h64Czqenhu+pt0wl84Rne0hq36jugHvXz6L8wGibdM/dq99AS78ctGE733FHgPwv5K7CF4iyWaJlj7CKR1F7UN/HcoFFUJ9yfsIsgYWHYOwniDo6NDVRyI+DI15CwrAQDcOBYP1wIAPDemTciVi3BHiFFS3ORuf32Fug69pIAuO/8mPWJP+seecxcXS4wLbxxru8LFMx3/fPv971QR1c7gZHPAIK9kQUFFVRm7g9giA+hhVFZFfLxzgBBJXpTuQoTDusjTlt+l3om8w692vpMuccZ0/CEAv6vM1P7g+vWur/e6jmi5NvA291bv3ijCRfN6wrYLbhuZx4JqT0R6T/CY/+jAKpfvl/ktqe6KNK/lQJqh9Ug9FO5+/w+lNZyOXFgIlQbijC3DgdyCK2rHlnBS67XCWDixQUYeCC/slhRo0mtkphWg+mNnJT5vq7GFEpLupl4pRfi/HK805Pzj4GjdBZXxTcHzSEwdDZRXb7puoZrmATLQo+jbAqz4UgUs3EKcjXIt66HIeaL8qr6hVDZ51Xhuk+iY9E06DijnqGZ7zIRfXFu3cbSvWwwuPCjtY1qxzlTaG1esWPMI9Mgc="
    - secure: "gpwW3DYatwCSW/AreaYU+GjxunNwTfOjApYv5l5fASCE57H82koAxiJUc1Od+W0lwy7Z/6c9gL7x0AoNOlKwYgISVBb9nJ4hZNqTveQKYEYIVYFqY7COkczIktj5500tMqVZxASrva6yNIMic81sJHMH6bn0BGHgJ3+mygNZkh6ufpTO21ro4DcPsXDmij+zeXdR7OWN1VYUFAu+XUXWQGvEcj2lV2H2J23ei7EowVKH7Kh66+a606Qz6bK7T8p0pHRtnoFSmKzmZP/0kyMDh8gHQR5Rc7VXsvbdxyIlhLp6VBPQeSODDQ8nUn7tmkOVdpivm73sESuN/KP49U4UI5IM1JlaLrMJTV4S9XvvPcZeuV3fwcBKZy6m9lTuu/MlW+mY/w5uYmyjOnGtt+u6HQRD7TduiDfVttxJl+eF7YYEjNy6b9X/pz7vJaYshJOtzikQlb3fxFhqm4ASdSCCwqGalIP6wGr2scF+7q0jscGhsagYiOgt3HgFFX5TDVspzS4d0V2EAspvOEWifXiyHiBU94i0An7cmHXHr4mp5Q7GGhINNVfp5qfDN45fkIst0/303zdxoh60ctHTCodPnVUCXKWqLe9F5IzxsnAxbE62RDiFo7Ie5vck/RJSHALq6PnVxrinrlpx7OO9ym+74GmrGYLd+FTOFQqxyNTsHXY="
    - secure: "Oe0a+jCSrdw3sqG3hpMu5DkrpLJD4upkW2krWdq11ereul5JdHLfkGRVGPnzS6riEoSee5pzhTQKFdFRYMCslOiXn+wuKu0izXQ2Ye27vjvFQSN1DQkPlasH6Z6q8ATic2m4aoUyXojy/kgRvr/DfsAF+Mzirg/N81HnXqAP/dZka8LRJCsytmuaHTWMrtubrQ/lBtSCeppuXEjR4dhXu4BUL3qX1s9eGQ6WhKbyK5pjXxeP08uHyWqUIr5Pse7FJnCw8ua8mIYRtm+Ew265I886cfl0tC3DcZy+Jmo2KFTRK/OjU+2v6rWETUrBZpdoBPHkMUfKklGKW09Js2O3HkxEr3L9nhYtbxttJVWOGpHIvrDUnlCo1O/Lgv92oV3/0FybSiNiC4t+zZPyPesxEKcegEG5r/v5BSEVHiREePgovwpZ0zhyP9KbcG9SmC2RLx1sgPpBoxIOJg/NrYi++uf2gH8iLfZwSm+/tS5kUC3M7joPGvs1yU5Q8rriUKRhp41oEvvU7ZPjlZM0CdgxwT+wo0qX87BjD68J6UPp/wC0UPgbkv78FX3SLDxwFoptDpn+Id2IlJ85O+ZO8aF9di30kLv/WGULlXbGup8ZdCN9vkUPrZ0HKUD9ebKNe0KH/SEkRO56qYiZGwtdZ0X4sLLR2ALBpuRclPJY7udOVAY="
    - secure: "nR0lZwmrn+pxzr4e0KAlsTBpf3OJd0R+eH3sTpB06+Rk74NYfGTP1eMAxxUQu2v8Jk+VHV4nvR4HZnxTFvKyFS5isRPkpU/X/CTJ5R/WiACToA91qsX1AQ/mdDX5GbwWrf7wu+s+nUg1RVPXR74MAUr0Splf7te8ksNfXtvbZjuZE9rYhWBbTZW1g9gpYTvkYVQPNWwFvl/eqmpW55GhNYh5ffquS6tusbvC4391E8hrrFbEnIxw2Lfe3ibwaevFXuePwh2Exuzb9VwWReGQo/4NFSCriI/QiZ3YjEUTJ3pQcsosXS/TLEJAl1mrJ+EF1DD6zHUw+zgOLRKjSjI9cyst9PFaTblr6NUU34EhsubMtJ8vpm6IEdY6drXfh+bKlECAlIpV/Kv1ZXnYn2zSKW67lKFFdumH28j2UjSt1rtq+pslwJ6IRsMLeyqYTYDAcVxfBzItPkdbKiGoJJL6X+6EDb9Xjoxi1q9kxJonMuPtkgi/+xK6CzV0Y39ZEcU539lFAq6aCLiFTZU31fj81LY2jEEHY2JEmHxdLQ24pYlmgVaRvwdwn9kAVX5qFeD5lkgqxi/4JUK49ye6y5KMQjo3j/+CqdY5PKYmNkRKFvNwM98Ngdqp8z3w2twPVazwxP1DMeNcrhy5RPbagca1OWpj0uUVUvBPEiWHk2Q7DDo="
    - secure: "QRErL3hyvvllXYaimM3enlpxJiGdU7WMICxIgdqpTYeP9NwlrKoYyaWSHfPgD7QRD/CG3YnnGnhEAZGNXnJj6upw+tA6X9ayh89NCIkrddaJVQXkpn7YEqiqCmT+7OdGHu2H8P1GPvrA0hxl2nFY0OaoakYZN49j3XMMARCDcGpeo3KbIGctxNBuzJnlw7ycwP1iHb+arKejZogSzi4m4HqCqG7IjlbnZD58ouT33Mf6YQthXSK2N4PyrShNBtlnwnyYE4LkhlbKilHo/vPYnGvRTdoXF56dH6Vc+mg6kZWz6d/AHFYVExKK0o5n/nuRuwQN6QykJbEybPYKqvHDAUZvcwoCosCrb8JVVxv8NF2h1LLBzIc/dRDIdRjl3K8e+dRoilgxtXXtrVuyF7WXyvNnS7hfYJXciKpgQR8I6UpBwdkUZXZL4bWDGbANSZ/mQbtuoHEaTN3EBFOblsdSAqaeXVhpDh8NfWs7xe2H5orqhfEm8ZW6kmNvyKOrjZqXg6Wc7EyViDpYCOOn+H1vRSYH/1c7jhfVMhtkOkK9bmbOSP7kld8sKBNV3A+2mTxQe0sDTnqK1OTs3ivTMwdWl+qedwrucaV/dStquckQWzZw87FMfYCdta4rYaiiR0YR1D1AMLm/J7WxDvXpW0i/qoQwc7bJSPLuG3NxoMlqYKo="
    - secure: "BWxrbyCLdaYuUc//WETFDccn6Y4d/MFKpGW8tTLJKjze6v9Zjewlt+TDASN9r8bKJuwag3RA8dbWa+LX0CvlkQPeakgepajfAd51i6g8ckbz9JIU9J4yTGVhdddzULLai9JLdUeXOmg2m+RhOrIoxXbFFrTcyoyw06EY7YjW82heSj7xYPG/oIxACr5ObVM+cuvvltStANLV0+yRRSRrMEhEuxn7nNBT7WGbyIo+7wBjSMkZcSlOWfJfDnjnpnaFz4F/hDwCg+erJ+0H99AQgoM0TRaR+RzRvZL3BB4qTjbur9pP70rs9XBL5szqJFNJDn1PfFvFmqcb4Ir7EeX4qHdvaR9HJ0UEXZ4L81GRLpZsLBWrH1E9eCXfZn5JoFF0MSSCwyRkL7Gq9oUPsBzGKmolYIEZtuAil4syCom9viCpCpuJYoNaSo7DqA4FfBcZinahCtMiKkTdL1AWxUG8s8RDyQeBqUzS32ZG7I8bVnspNq8TGlWvJ0EX7aTsh4E15oh2RO0bNje6IoJpPYHx3BaLAuKn033v/pxnLQh6wu67pCbutlwttJ6mRbGTg/CKcfWimqtAH2F/wqnsY7qlYVmwKHuZLACOz7My0dzZ6zfwHcpGL9HGogmUiCn1P9F8PdSXCuB0Xg3aAk6BKOwNiSk6ztRu6BcM4G5sWSVHFgA="
    - secure: "KPC01meOCb5eWN8RkDn4KsXiicWpWufu1mumRaaxu8DNYi33fe+AC4O7anTZ88gRSih8PvVEFxjTI7DQ5CmUVuRmbZWaMD88UvzvcFXKKqFUU6hbU+c+ssEaYD8d04OJSnc6t5PoP8FjmB4q5TuRosG/PcGWUZeqeJMNTyVoXieCTftEvexAE2FkTTj5YYl8AbyHo0phN3FoIEqwvPZJZuZcIcZfcI0cxRySoc6ye3D2tJIU6sNIWfuqsrYZUrHeqYXSaLu57IikO16DRYM94eKZz8cB8ibc697bzXEMjUUZOc7uMZ9JtJescLdGwLOyS6YxQE2mFETO7J7Yo05Igb5BuWoEIxmwpQOA0VlhEVXUYxxA25wD4Oe7HyC2ZqhmUhGIQRZ5TKi2hd+W4HyBJ3fBTbVcnOIY6hdQjvxhzD2QRXEFkS1vYqWbu9nFskjFgEIr9SI+7RgHVE+6pgXp4h7Ezl+YY6UtbFOcRf4oZaEUSMQUIEmhPm0eGwsatdi+4VtV73yph53YNIjLss5f09e5UEnPYb0epN0QdwDG6q7ElFZgappJiVvixzUV2SOsXMytaLhHd+QNpZUka1S7J6oYz0/md5sMP21ecsL3qsm/R82Wvl7RNEzG6jAeruch/w1edskccs5tASdt/Gd2VgUKqiplhOmpRR/5EB8jDMY="
    - secure: "HbV7Dd6dLQhOadOBimacVrxxW9irXdtsCoqu3AtpZWXbWDX6X+P80KJ9GerPw/RTM5BZyyRAw3cYq+wTDHxaVUdoGpSMIEUH3oVRU9JRPdfhsrgqIb0yEKx+Ka2FPSmgHLAkRjqh8lVfJ30DU12xNxtZRUPx4mu1qXso7nvNDJuK/OwvxROivdBCMe050lVJoiOk2W2RAKX7sOOs2ewpot7hTlydMky7ARyItQ8CTULzWHR1l5LQY5N+c8jSOcQNEOdpxGSiK+tf4dNga+pP0D6DApNU8Jmqgs31l4wR5E7OPvi7xuNBM5KYWUmlMRhPyyIhPnbMbCEFvYOkmKApJY+nsmMesv0fp+BFI815eGKva10pRPedua32kpKPlGNkLOsyWQmMEcGquUExXZ6pin86YAEz24eIvmnvgLPe65yNZXxex3RgCH2BwITd7LkqUPFYYkFKMwHoRIbdnrypy/Q5uuOFqEjdzqa/mjDb54TVGPV2ZijWwWwXIy28G5DGtm4nGC7cK0430qdza//MJ6YCBh21JQIVN2mIglT62C/eck0vUHxkjQxMuKg6sGQjSbnv4Ocd8P5ZZ2BnyhPMVIHNwYffkHcnhzFEoeJ6Y+tUJvWosIlOvMVNlm8QoyHszMTk3jsdvgeh/p0vUwaqe59U4EEQh/Hjsvj75ZTPe4U="
    - secure: "Xuz6e3eFVQOkHHHK+/NPPzggdU8GICyxpDFm8VwmreBMLK7K7pzHBZH6EQv51sUZwmV3gcRsfAnysA23SvxyL1ou2EEg6348+t6F3pzLX3qloGHgQ6Dese4YxBoldNT/aRE8wlM7L307us4aEmCk+tkAwM8jHaHzAekggY2Wtx2R7k3s22SXPKkdavNlAPYFhqgU++mxssW1wEvCr3c8hbxgx/4QnEHf/BYBGzhkIYI6KO9BePm2cpjwWksrR0iWTkURDU9uHavFem0dJk6WeQLkRmQDnh7NIJKkVpKiFfb4ewzSKq4VO0lXAWBPC3/V672ZKkqBrggHEHunyFNVc44MGktcFSvCyZaxGa1t1Lx5hVkhsdfL6Nkx2gDgwjPM2eE8ZtI/xxhfsR2EV62EkX2t6+8CvZpPFQt8Fh5//FqlB8m4ZHS4O48YZx0IzCs8Ge6h0xdjArAoKMbZ0RmnXLY9Et2ghn61sChHfUtdZjA08/oJK2AUJHb/1dmfzh0Abs1CUK39XWwCwkbz9ghDOhq39lt9cuXehSNNffpOqTV9/zs1KhMAUvEdA0ZWwFxzvDtAb+RWOV5JHtMxgeJWpplZ3iZT0tharoxqsbFxl1qEaJx8wdqpS7ggWV9GCXFW3j+vCGav3iHBUjsEOI/YirqYAuBqx94WB/ep7jadR1E="
    - secure: "pKJ/ZaY7zGlAtgq9xcZu6f0nTPk3Ivhb5M+Bi2jgiUHqg4mES0dBSTquF0lCSwdpjV+zq2xWvlAzTCdNsZJVvxXsNENo6xevjVrM73zYWJUmcTLYCeXBaEa1L7heNFCF9ImXjhDPjrvcY1CTkzbfgJb4kVlS5E9FAD/Vtc9NOpeY3IpctMQP/kiPEGrZLkO/hUc0TkvlweT0+8Z20ge4ELCmme85dxX1ZuQQjanLLphYnSyNnjbiaMvAwhPDJPMDroorxrbTuGFB0cPofXv5OKhyokUw+90wulf21leuXXFBOWuhfT7i09NHTnFnMz/TisiI/d1iXPRFCu4to/R9+SueD0WreAjB2e3ptr8ausFaeONu4YDyX6xyCXet6/3cY1lTYBu6gqcvVSLWODJVq+KFDzVsrPA4yQ/1Pon+GisnBTvudHSpBO1XcMPoo+yDh8eyD/o8prV96fRW1L9yyevGzz3OjWeAf0BxIyob1BOfGCbC3cj7xSnyrHMaTD7ddcS2uv7K2xphb/tb4sA+v9le4O7c58OoUZz2Ir3OPgdFFjn+R0Ms0HONzVutwa9OqhdRrcjxYmxLIsjwTh+wNkBvCwu6IpXv1lLZfdDRda2D7T93yE/2qZzwLdcld0BC6aYmQpBoU5aQ/2qInD3qcJSOZuuk0o8g70Y9UkXqYzI="
    - secure: "K2wJFLc1EROIcg50X9Yf7UKdC/h+ShBWU8YihnbomleqbDSX1HvtTz2l5WvfxhfvHpEviNIsyB8s8IakWHhCZ6lmCLHfSFQ2O8QSqnOCDhmYVHvgS5xe2JnCsx+7iNFjiuGXzWhX1ypmqSjs9Uu9xQJ5nIfkGKmDkdWdVfyy37ZMi87ggUXisLEHLTOvdbmXFb1vlY6O3bD8x9g06vaWGfaURL2aNEzVwiYQ1X7lTKvn23y3rJXiYN0ka1KIIReEP49uMy6YuBV/tlU1UcL8+fdSELjgbRWoPanjxKVBk5/mDlGejB60B61Jj01UZtRKa0l5MDN43YYMGr5qWNEotYd/MzuNan6ZMT+544WFg/3rM/rnO0QYSuFcKcfj6/w9ipgdxSsLv9fzjxp63A+vcykhsexdI+bBLGzV60RftAq8ha1fLA3fUi5agWoOvgn/DRejT+les/ko+vHvL4xyv+i/cNVSV3wVJXE49M4qoD6oqpSyTFxwV2pSTh13UEjwPaEeIQ3mXlkP+XrNmIkJW3poXdV5HozLk3krfXTvYFJc1PaQ41rSzdNcsq+9qR4N4+CIonVJ74wToP1fFSTgqj0D+mbvAU7o+F8O51FPz9Dn9qDDErUG372nzidu03K5z6AD4wvnYhUS+CWgHGkU30ImRnbLp8r1KkHODFPTGGg="
    - secure: "LukD6deupDgYLJRuYt1k9cvxwqgGwA86E0MYBBsMDjYtXiiH/rnmYdDgsVEs5cndTjysDjyHdCIokGdWtD0lyOGgObVvBQwGdEHSWdvJpL/zgn9XT9vRwngQpCTiiIdhSksYt3a6ytpqYYBWX9HVq3imAV7A3AaS//mJNuzWwHf1i8KWHRu30Yw4+YVMyyqW+qMy20CNFRKd5SiRnbyJAKc5Ng8HwLeOC/dVO8YvG2Mpegv1ZMe1Nuc9/4EvBBR5wfXK/kVHSI7r1FmX1+MlIhHSxtzwAWByQKPS4wGPHnHEoTl/d7o9xvkbaRMvMHzYbCpwoTQy5+DaOdbkvH/cZTADe2czbFOE0lje3XQbrrSrpbKtS484H6aqn5umMmip3TiBDFGcLntK6g8z8KNpTlkMlK+Bq/AKvARARkwpRAjpYMeo4zpTh9UZ+gHKrabjD91aOlRuHTsu0ZVG7M6s7khJW5POCeRdQSOrz+Ss44A4T10udEKifPnulLPPkCt+DxiLkEfOSMWrhqM3AEODT4FF08qt1nzGMZuSx+aB87xSvApshDmqQgpj6706/Qlj7u7mexzXgO38Zhqn+hgox8J7EChYagvds/SeUy6xojBz2JWJOqIbpS2D1I8zlvbE09F6B3g9ifIFS5CiQ+D9td51uxTQCtmYwMI0VSX+EfA="
    - secure: "RnwTEz65/fq4Pj3L9u5Gi7k3URn4TFw4pPLC3VVjnDLD0ZinGETQVfc642l3TJiyxG6QXcmW4thq+aNBRh+bbcSwqQJ+C2Fj0XLU1/TBLHvtcHXKknI3iJX2kRXm5IN43zuJvI9j2y5G76q5lOgwUjDEVPlpEgQm1lIYYbeayO3QHM4eTETSCZMuECFfCZpKf+jR50u4kdKxyuadF/QdNjdzj42LfzU6cqE/gwbHRXQ0t7OvWrP4uZeFOg5FB3KQD2IT+SnKkSDkxCxswjcg8wlt2PQA+/HJYvYELV6z//V2pth8DWkyVq67XIv7SJfqNlM+ocui9XNJFerDY55GdjpI+jwcYfWVSHGtdS7WONySksqG73Y0Q6PO8yEXYmXz+D29+JJbpmkzgUfaJrOVIV37gnQzcdc9cl5779xSUe6srmUNe+2cgHTz9pdTrEw6xhZF2sT9dwOeFrNfMrJL+h9sryG4PjL1Nw2txK8BvfHtRD7vi3Jg7RGRoqO8FV1+OJU9Fj+z/GWKiw+r36oy7nn77wzRFSZ8xjdqmWWEo/G675EKOiw+qQNddi6ubi+slZ8nKB2TRiSOZy5pIUpmyIeoecP9lTycqRJOPduB03UiHSKsVCVNlxHLjC7sNn+7wpWqHdBxqlscaI6lI+KpAWHGunkgBky3LFogtx6xKsY="
    





install:
  # Vars
  - echo $CODE_SIGN_PSWD_DICT1
  - echo $CODE_SIGN_PSWD_DICT2
  - echo $CODE_SIGN_PSWD_DICT3
  - echo $CODE_SIGN_PSWD_DICT4
  - echo $CODE_SIGN_PSWD_DICT5
  - echo $CODE_SIGN_PSWD_DICT6
  - echo $CODE_SIGN_PSWD_DICT7
  - echo $CODE_SIGN_PSWD_DICT8
  - echo $CODE_SIGN_PSWD_DICT9
  - echo $CODE_SIGN_PSWD_DICT10
  - djgnekrjbvkerjb
  - export RELEASE_NUMBER=$(cat App/QmlImports/easyDiffraction/Settings.qml | grep 'appVersion' | sed 's/.*"\(.*\)"[^"]*$/\1/')
  - if [ $TRAVIS_BRANCH = "master" ]; then export TRAVIS_TAG=v$RELEASE_NUMBER; else export TRAVIS_TAG=$TRAVIS_BRANCH-v$RELEASE_NUMBER; fi
  - export RELEASE_TITLE=easyDiffraction-$TRAVIS_TAG
  - echo $RELEASE_NUMBER
  - echo $TRAVIS_TAG
  - echo $RELEASE_TITLE
  - if [ $TRAVIS_BRANCH != "master" ]; then export NOT_MASTER_BRANCH=true; else export NOT_MASTER_BRANCH=false; fi
  - echo $NOT_MASTER_BRANCH
  # Python
  - python --version
  # PIP
  - python -m pip install --upgrade pip
  - pip --version
  # Install
  - pip install requests
  ###- pip install cryspy==0.1.12
  ###- pip install PySide2==5.13.1
  ###- pip install pyinstaller==3.5
  ###- pip install pytest
  ###- pip install pytest_mock
  ###- pip install pytest-cov
  ###- pip install pytest-qt
  ###- pip install coveralls

before_script:
  #- python Scripts/CompilePyResource.py
  ###- python Scripts/CopyMissingLibs.py $TRAVIS_OS_NAME
  ###- python Scripts/MakeDist.py $TRAVIS_OS_NAME

#script:
  #- pytest --version
  #- if [ "$TRAVIS_OS_NAME" == osx ]; then export PYTHONPATH=.:App:App/PyImports:$PYTHONPATH; pytest --cov=App Tests; fi
  #- if [ "$TRAVIS_OS_NAME" != osx ]; then python runTests.py; fi

after_success:
  ###- python Scripts/MakeInstaller.py $TRAVIS_OS_NAME
  - python Scripts/SignCode.py $TRAVIS_OS_NAME $CODE_SIGN_PSWD_DICT $CERTIFICATES_ZIP_PSWD
  - zip -j easyDiffraction-$TRAVIS_OS_NAME-v$RELEASE_NUMBER.zip dist/easyDiffractionInstaller*
  #- coveralls

#cache:
#  directories:
#    - ~/easyDiffraction

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Travis CI"
  - git config --local user.email "travis@travis-ci.org"
  # This writes a changelog. If wanted
  #- '[ "$TRAVIS_BRANCH" != master ] || cd ../ && pip3 install gitchangelog pystache && echo "output_engine = mustache(\"markdown\")" > .gitchangelog.rc && gitchangelog ^$(git describe --abbrev=0 --tags) HEAD > CHANGELOG'

deploy:
  - provider: releases # GitHub repository
    name: $RELEASE_TITLE
    api_key:
      secure: "s3uqRW5prwmZp8dFSroXQCUBOFOCVU10iSGMVfBCtn51HDmF/RXDlQw7UJHs8vJJbtY+0tQ2yByCj5nah6VzaXKVyvxl7/VXGgB67LkHaI4idKV8HOqcSShJ1sxGapvMC3u5Ezx8tg3cK09SJnSFXq/xk9NoTdmxuFDX6X9P3jRq/CKM5mkHkOiUWLeU86sulJiBIBdcYoFwIXOKQE5KlDDBFDiI/qnEC98B4lKMSzRQB5VQEXeW+Z4f7KsK7/aS8H+Tw0sA+P81TN8CVXBeWAhBpEzrSAxLGEMRTP5GY/AkiJbdBuJMmHcc1t0S79OBsKQcrV2Yl9CtN4/WuvIH2caX19z39AvfjzDyHMnkDzN0XBv5fvQYla/45PxdmQf8O6GaiITXewBu+1DT9nQzLLaLh6GHz/zdGZeO2/ivwBMQnd8A3+B8YaO5/2dYGndAPDt06ECQBKI6RGvEBfTjApSTnuX07CjAwkXyg39uZo4KRtF1FGSjZdcNaDQGByPNHu4IOM60xDgM7VHI0EBz5YfZMpVs0sVTIsnwe7m+tFzRa00E/mlFdPCUvpYeZxgBJpNIvoBA53R7hUcvPd/xNeTfiT7tF08cAc3rdm+Mmdeewifn91SGunUBwLiNBVLB6YVlIfj2Btkce5fgdLTkVGnBlnawGAZtJwtH1Z6EJR4="
    skip_cleanup: true
    draft: true #$NOT_MASTER_BRANCH # true: only repository collaborators can see
    overwrite: true
    file_glob: true
    file: easyDiffraction-*.zip
    on:
      all_branches: true

after_deploy:
  -  |
     if [ $TRAVIS_BRANCH = "master" ]; then
        cd ~/
        git clone https://github.com/easyDiffraction/easyDiffraction.github.io.git
        cd easyDiffraction.github.io
        git remote set-url origin https://$GH_TOKEN@github.com/easyDiffraction/easyDiffraction.github.io.git
        cat index_template.html | awk '{gsub(/RELEASE_V/,"'$TRAVIS_TAG'")}1' | awk '{gsub(/RELEASE_N/,"'$RELEASE_NUMBER'")}1' | awk '{gsub(/RELEASE_D/,"'$(date +'%d %b %Y')'")}1' > index.html
        git add index.html
        git commit -m 'Bumped release links [ci skip]'
        git push origin HEAD:master
     fi

notifications:
  slack:
    rooms:
      - secure: "t0nR618a2fr2EDpyfKWBBkcf5MJ549P732EGvN9gwXVYvl4z977KSSH6uPEw7/KmMec9BhMg882hJidoeh1XgvUQOiVan4jrlvn16z2INPWh/dloXOZN5YWz87tSLR1jn1tDaKSK7gaOF5HAosPbQ2/UriUaAG9d9GHJKJzCogNDAFwFge3K/b4KJr1kYpwS5Vd5K99peWnsrNYBz1M4+Xjc49cd5t5FKULtFduX0Zb25t3dQ25u9LfGQ5lyH65UNSqcu9DP4RZmX00KLYNnIOYtzuyWvehPhisoBozA+Fpuly2IaFPVswtHqO/h9kziyYBBcnEAvG0U+KHmkJy21vDHN5+yPoHlcuAr0Q95C7GEpUT/JVAeNggxWWF4WLYrcTbZXWGt69pBhuFUAZRnbzSV+wBF5ZAOK/5W9TvxYMM1uS9AqdLEmUQdtIGrj2VIDS1na0dielNMnOhBc0Xgap2as/Kb1aEkPuSA6kENDOGXrw1Vs0VjFK3iWOlyzHbfHdHWM1/WZOO2sZRNjdTgWS5x5UXJbozTcM5mzcAkZ21vVpVG5h7LQI3cMPpD45Hmtmnko6S+7FlaknesIeXXhZPwILxN12LtbBo7AkUqtdi/w4Do7CAA++hNJRQx2txa9Mfi6R9XhNccc9+3Mto6lw5hW9mDmb2b1TlrLksW5Ew="
    on_success: always
    on_failure: always

#https://docs.travis-ci.com/user/job-lifecycle/
