language: python            # this works for Linux but is an error on macOS or Windows
matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      dist: xenial
      env: 
        - SEP=":"
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11    # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      env: 
        - SEP=":"
    - name: "Python 3.7.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python
        - pip3 install pypiwin32
      env: 
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - SEP=";"

install:
  - python -m pip install --upgrade pip
  - pip3 install PySide2==5.12.0
  - pip3 install scipy
  - pip3 install numpy==1.16.4
  - pip3 install https://github.com/pyinstaller/pyinstaller/archive/develop.tar.gz

before_script:
  - if [ "${TRAVIS_OS_NAME}" = "windows" ]; then
         echo "Windows - Should copy shiboken2.abi3.dll"
      ;
    else
         echo "UNIX"
         if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
             echo "OSX - Should copy libshiboken2.abi3.5.13.dylib"
         ;
      ;
    fi
  - pyinstaller App/easyDiffraction.py --noconfirm --clean --windowed --onedir --log-level WARN --add-data "App"$SEP"." --icon App/imports/easyDiffraction/Resources/Icons/App.icns

script:
  -  echo "This is whre I run tests"

after_success:
  - echo "This is where I do code coverage and deploy"
