language: python            # this works for Linux but is an error on macOS or Windows
sudo: required
cache: pip

matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      dist: xenial
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11    # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.7.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      filter_secrets: false
      before_install:
        - choco install python
        - choco install zip
        - choco install curl
        - choco install grep
        - choco install sed 
        - pip3 install pypiwin32
      env: 
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH

## We can secure environmental vars
env:
  global:
    secure: "Di2A3xkThM7/Y7idHv22RUO/CNGi9Vdt4esBTg88miwM1yy5mxa55/1ZOYLjGroVBs+cJUwHRC0QFSLCRsTpY20PCLw0RUHXkf0p24xCU8PlaPiSjxWHQOTwUlLMsskHvsC9YHeYqf5d4pPEW14OE33pg3osYKobQOdFda9drMOM48Vug+X9veO0b65vzcjNcXpHjcMEAAkzYAAUXOXtt9PZHhnC65XNMLWIXRyVuVn5iGncHA8A3E+4J2g2LCdgRktvB6mx0oNZdzAA3+7W+D/ecBgBMJU8x53ICvdwReXEO0Jtm0ZG5Zwr9H3VUYw8F+M3GyG6/idgvesqUZ9RZ0BHqHIwd+bSH73gAn70OfiwlSCVq1Ms4UOIAFJ5wCHIRA31nLsW087PA5fp3Z1UmWKjeFb4nFEy8iOjEoSeEZP+PUP2YEdQ1jSqP5wriGUX8NfEW9875vNGqv104iixopRGVMEOZlCm5AXA4J05xke7FhUkQDGDLtnoOr4KOt/sFcniYK2YvtPTy4bC4gL7//MfiCGFtj6gxhfa0k8Gv6A6gnMgmmWgy2I3x0BeGbunC818z53+Fx7srrCbD0OGDCbjCmWpAPveCljamJO1imM7FesuKt52hZ2QmwDMbDVPvUiBeOi0ygVW9Hn57+90IxhWF3fUA2qMyAvMMSEEG4s="

install:
  - python -m pip install --upgrade pip
  - pip3 install PySide2
  - pip3 install scipy
  - pip3 install numpy==1.16.4
  - pip3 install https://github.com/pyinstaller/pyinstaller/archive/develop.tar.gz
  - pip3 install pytest
  - pip3 install pytest_mock
  - pip3 install pytest-cov
  - pip3 install coveralls

before_script:
# Fix python packaging, becaues it sucks
  - if [ "$TRAVIS_OS_NAME" == windows ]; then cp C:/python37/lib/site-packages/shiboken2/shiboken2.abi3.dll C:/python37/lib/site-packages/PySide2/; fi
  - if [ "$TRAVIS_OS_NAME" == osx ]; then sudo cp /usr/local/lib/python3.7/site-packages/shiboken2/libshiboken2.abi3.*.dylib /usr/local/lib/python3.7/site-packages/PySide2/; fi
# Compile qrc (qt resource file) into python file
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then pyside2-rcc App/QmlResource.qrc -o App/QmlResource.py -no-compress; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then pyside2-rcc App/QmlResource.qrc -o App/QmlResource.py -no-compress; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then pyside2-rcc App/QmlResource.qrc -o App/QmlResource.py -no-compress; fi
# Make the app
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then pyinstaller App/easyDiffraction.py --noconfirm --clean --windowed --onedir --log-level WARN --add-data "App;." --icon App/imports/easyDiffraction/Resources/Icons/App.ico; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then pyinstaller App/easyDiffraction.py --noconfirm --clean --windowed --onedir --log-level WARN --add-data "App:." --icon App/imports/easyDiffraction/Resources/Icons/App.icns; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then pyinstaller App/easyDiffraction.py --noupx --noconfirm --clean --windowed --onefile --log-level WARN --add-data "App:."; fi

script:
  - pytest --version
  - if [ "$TRAVIS_OS_NAME" == osx ]; then export PYTHONPATH=.:App:$PYTHONPATH; pytest --cov=App Tests; fi
  - if [ "$TRAVIS_OS_NAME" != osx ]; then python runTests.py; fi

after_success:
  - coveralls
  - cd dist
  - export TRAVIS_N=easyDiffraction-$TRAVIS_OS_NAME-v$(cat ../App/Imports/easyDiffraction/Settings.qml | grep 'appVersion' | sed 's/.*"\(.*\)"[^"]*$/\1/').zip
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then zip -r $TRAVIS_N easyDiffraction.app; fi
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then zip -r $TRAVIS_N easyDiffraction/; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then zip -r $TRAVIS_N easyDiffraction/; fi
  - cp $TRAVIS_N ../

#cache:
#  directories:
#    - ~/easyDifraction

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Travis Builder"
  - git config --local user.email "travis@travis-ci.org"
  - export TRAVIS_TAG=v$(cat ../App/Imports/easyDiffraction/Settings.qml | grep 'appVersion' | sed 's/.*"\(.*\)"[^"]*$/\1/')
  - '[ "$TRAVIS_BRANCH" == master ] || export TRAVIS_TAG=$TRAVIS_BRANCH-$TRAVIS_TAG'                
  - export RELEASE_TITLE=easyDiffraction-$TRAVIS_TAG
  # This writes a changelog. If wanted
  #- '[ "$TRAVIS_BRANCH" != master ] || cd ../ && pip3 install gitchangelog pystache && echo "output_engine = mustache(\"markdown\")" > .gitchangelog.rc && gitchangelog ^$(git describe --abbrev=0 --tags) HEAD > CHANGELOG'

notifications:
  slack:
    rooms:
      - secure: "t0nR618a2fr2EDpyfKWBBkcf5MJ549P732EGvN9gwXVYvl4z977KSSH6uPEw7/KmMec9BhMg882hJidoeh1XgvUQOiVan4jrlvn16z2INPWh/dloXOZN5YWz87tSLR1jn1tDaKSK7gaOF5HAosPbQ2/UriUaAG9d9GHJKJzCogNDAFwFge3K/b4KJr1kYpwS5Vd5K99peWnsrNYBz1M4+Xjc49cd5t5FKULtFduX0Zb25t3dQ25u9LfGQ5lyH65UNSqcu9DP4RZmX00KLYNnIOYtzuyWvehPhisoBozA+Fpuly2IaFPVswtHqO/h9kziyYBBcnEAvG0U+KHmkJy21vDHN5+yPoHlcuAr0Q95C7GEpUT/JVAeNggxWWF4WLYrcTbZXWGt69pBhuFUAZRnbzSV+wBF5ZAOK/5W9TvxYMM1uS9AqdLEmUQdtIGrj2VIDS1na0dielNMnOhBc0Xgap2as/Kb1aEkPuSA6kENDOGXrw1Vs0VjFK3iWOlyzHbfHdHWM1/WZOO2sZRNjdTgWS5x5UXJbozTcM5mzcAkZ21vVpVG5h7LQI3cMPpD45Hmtmnko6S+7FlaknesIeXXhZPwILxN12LtbBo7AkUqtdi/w4Do7CAA++hNJRQx2txa9Mfi6R9XhNccc9+3Mto6lw5hW9mDmb2b1TlrLksW5Ew="
    on_success: always
    on_failure: always

deploy:
  # This is where I deploy the results to github
  - provider: releases
    name: $RELEASE_TITLE
    api_key:
      secure: "s3uqRW5prwmZp8dFSroXQCUBOFOCVU10iSGMVfBCtn51HDmF/RXDlQw7UJHs8vJJbtY+0tQ2yByCj5nah6VzaXKVyvxl7/VXGgB67LkHaI4idKV8HOqcSShJ1sxGapvMC3u5Ezx8tg3cK09SJnSFXq/xk9NoTdmxuFDX6X9P3jRq/CKM5mkHkOiUWLeU86sulJiBIBdcYoFwIXOKQE5KlDDBFDiI/qnEC98B4lKMSzRQB5VQEXeW+Z4f7KsK7/aS8H+Tw0sA+P81TN8CVXBeWAhBpEzrSAxLGEMRTP5GY/AkiJbdBuJMmHcc1t0S79OBsKQcrV2Yl9CtN4/WuvIH2caX19z39AvfjzDyHMnkDzN0XBv5fvQYla/45PxdmQf8O6GaiITXewBu+1DT9nQzLLaLh6GHz/zdGZeO2/ivwBMQnd8A3+B8YaO5/2dYGndAPDt06ECQBKI6RGvEBfTjApSTnuX07CjAwkXyg39uZo4KRtF1FGSjZdcNaDQGByPNHu4IOM60xDgM7VHI0EBz5YfZMpVs0sVTIsnwe7m+tFzRa00E/mlFdPCUvpYeZxgBJpNIvoBA53R7hUcvPd/xNeTfiT7tF08cAc3rdm+Mmdeewifn91SGunUBwLiNBVLB6YVlIfj2Btkce5fgdLTkVGnBlnawGAZtJwtH1Z6EJR4="
    skip_cleanup: true
    draft: false
    overwrite: true
    file_glob: true
    file: easyDiffraction-*.zip
    on:
      branch: master
  - provider: releases
    name: $RELEASE_TITLE
    api_key:
      secure: "s3uqRW5prwmZp8dFSroXQCUBOFOCVU10iSGMVfBCtn51HDmF/RXDlQw7UJHs8vJJbtY+0tQ2yByCj5nah6VzaXKVyvxl7/VXGgB67LkHaI4idKV8HOqcSShJ1sxGapvMC3u5Ezx8tg3cK09SJnSFXq/xk9NoTdmxuFDX6X9P3jRq/CKM5mkHkOiUWLeU86sulJiBIBdcYoFwIXOKQE5KlDDBFDiI/qnEC98B4lKMSzRQB5VQEXeW+Z4f7KsK7/aS8H+Tw0sA+P81TN8CVXBeWAhBpEzrSAxLGEMRTP5GY/AkiJbdBuJMmHcc1t0S79OBsKQcrV2Yl9CtN4/WuvIH2caX19z39AvfjzDyHMnkDzN0XBv5fvQYla/45PxdmQf8O6GaiITXewBu+1DT9nQzLLaLh6GHz/zdGZeO2/ivwBMQnd8A3+B8YaO5/2dYGndAPDt06ECQBKI6RGvEBfTjApSTnuX07CjAwkXyg39uZo4KRtF1FGSjZdcNaDQGByPNHu4IOM60xDgM7VHI0EBz5YfZMpVs0sVTIsnwe7m+tFzRa00E/mlFdPCUvpYeZxgBJpNIvoBA53R7hUcvPd/xNeTfiT7tF08cAc3rdm+Mmdeewifn91SGunUBwLiNBVLB6YVlIfj2Btkce5fgdLTkVGnBlnawGAZtJwtH1Z6EJR4="
    skip_cleanup: true
    draft: true
    overwrite: true
    file_glob: true
    file: easyDiffraction-*.zip
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^master\/.*$

after_deploy:
  -  |
     if [ $TRAVIS_BRANCH = "master" ]; then
        git clone https://github.com/easyDiffraction/easyDiffraction.github.io.git
        cd easyDiffraction.github.io
        git config --global user.email "travis@travis-ci.org"
        git config --global user.name "Travis CI"
        git remote rm origin
        git remote add origin https://$GH_TOKEN@github.com/easyDiffraction/easyDiffraction.github.io.git
        cat index_template.html | awk '{gsub(/RELEASE_V/,"'$TRAVIS_TAG'")}1' | awk '{gsub(/RELEASE_N/,"'$(cat ../App/Imports/easyDiffraction/Settings.qml | grep 'appVersion' | sed 's/.*"\(.*\)"[^"]*$/\1/')'")}1' | awk '{gsub(/RELEASE_D/,"'$(date +'%d-%m-%Y')'")}1' > index.html
        git commit -m 'Bumped release links [ci skip]'
        git push origin HEAD:master
     fi