language: python            # this works for Linux but is an error on macOS or Windows
sudo: required
matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      dist: xenial
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11    # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.7.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python
        - choco install zip
        - choco install curl
        - pip3 install pypiwin32
      env: 
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
  - python -m pip install --upgrade pip
  - pip3 install PySide2
  - pip3 install scipy
  - pip3 install numpy==1.16.4
  - pip3 install https://github.com/pyinstaller/pyinstaller/archive/develop.tar.gz

before_script:
# Fix python packaging, becaues it sucks
  - '[ "$TRAVIS_OS_NAME" != windows ] || cp C:/python37/lib/site-packages/shiboken2/shiboken2.abi3.dll C:/python37/lib/site-packages/PySide2/'
  - '[ "$TRAVIS_OS_NAME" != osx ] || sudo cp /usr/local/lib/python3.7/site-packages/shiboken2/libshiboken2.abi3.*.dylib /usr/local/lib/python3.7/site-packages/PySide2/'
# Make the app
  - '[ "$TRAVIS_OS_NAME" != windows ] || pyinstaller App/easyDiffraction.py --noconfirm --clean --windowed --onedir --log-level WARN --add-data "App;." --icon App/imports/easyDiffraction/Resources/Icons/App.ico'
  - '[ "$TRAVIS_OS_NAME" == windows ] || pyinstaller App/easyDiffraction.py --noconfirm --clean --windowed --onedir --log-level WARN --add-data "App:." --icon App/imports/easyDiffraction/Resources/Icons/App.icns'


script:
  -  echo "This is whre I run tests"

after_success:
  - echo "This is where I do code coverage and zip/dmg"
  - cd dist
  - export TRAVIS_TAG=easyDifraction-git.$(git rev-parse --short HEAD)-$TRAVIS_OS_NAME.zip 
  - '[ "$TRAVIS_OS_NAME" != osx ] || zip $TRAVIS_TAG easyDifraction.app'
  - '[ "$TRAVIS_OS_NAME" != windows ] || zip $TRAVIS_TAG easyDifraction.exe'
  - '[ "$TRAVIS_OS_NAME" != linux ] || zip -r $TRAVIS_TAG ./easyDifraction'
  - export tmpfile=$( mktemp -t transferXXX )
  - curl --upload-file ./$TRAVIS_TAG https://transfer.sh/$TRAVIS_TAG > $tmpfile
  - cat $tmpfile 
  - rm -f $tmpfile

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Travis"
  - git config --local user.email "travis@travis.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

#deploy:
##This is where I deploy the results to github
#  provider: releases
#  api_key:
#    secure: "s3uqRW5prwmZp8dFSroXQCUBOFOCVU10iSGMVfBCtn51HDmF/RXDlQw7UJHs8vJJbtY+0tQ2yByCj5nah6VzaXKVyvxl7/VXGgB67LkHaI4idKV8HOqcSShJ1sxGapvMC3u5Ezx8tg3cK09SJnSFXq/xk9NoTdmxuFDX6X9P3jRq/CKM5mkHkOiUWLeU86sulJiBIBdcYoFwIXOKQE5KlDDBFDiI/qnEC98B4lKMSzRQB5VQEXeW+Z4f7KsK7/aS8H+Tw0sA+P81TN8CVXBeWAhBpEzrSAxLGEMRTP5GY/AkiJbdBuJMmHcc1t0S79OBsKQcrV2Yl9CtN4/WuvIH2caX19z39AvfjzDyHMnkDzN0XBv5fvQYla/45PxdmQf8O6GaiITXewBu+1DT9nQzLLaLh6GHz/zdGZeO2/ivwBMQnd8A3+B8YaO5/2dYGndAPDt06ECQBKI6RGvEBfTjApSTnuX07CjAwkXyg39uZo4KRtF1FGSjZdcNaDQGByPNHu4IOM60xDgM7VHI0EBz5YfZMpVs0sVTIsnwe7m+tFzRa00E/mlFdPCUvpYeZxgBJpNIvoBA53R7hUcvPd/xNeTfiT7tF08cAc3rdm+Mmdeewifn91SGunUBwLiNBVLB6YVlIfj2Btkce5fgdLTkVGnBlnawGAZtJwtH1Z6EJR4="
#  file: "FILE TO UPLOAD"
#  skip_cleanup: true
#  draft: true
