language: python            # this works for Linux but is an error on macOS or Windows
sudo: required
cache: pip

matrix:
  include:
    - name: "Python 3.7.1 on Ubuntu Linux 16.04 (Xenial)"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      dist: xenial
      env: BADGE=linux
    - name: "Python 3.7.0 on macOS 10.13 (High Sierra)"
      os: osx
      osx_image: xcode9.4 # osx_image: xcode11 --- Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 -m venv "$(dirname "$0")"/.python-venv # create virtual environment
        - source "$(dirname "$0")"/.python-venv/bin/activate
      env: BADGE=osx
    - name: "Python 3.7.4 on Windows 10.0"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      filter_secrets: false
      before_install:
        - choco install python --version=3.7.4 # instead of 3.8
        - choco install zip
        - choco install curl
        - choco install grep
        - choco install sed
        - pip install pypiwin32
      env:
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - BADGE=win

## We can secure environmental vars
env:
  global:
    - secure: "iUDKM5LbuZIrxqYewO4g8GKbpCvdIwbQckYVX9tj9pP9outFNzLicu7gGpL3gSkl52kzWQk8wtsE27Yx4EYE4i5N6h64Czqenhu+pt0wl84Rne0hq36jugHvXz6L8wGibdM/dq99AS78ctGE733FHgPwv5K7CF4iyWaJlj7CKR1F7UN/HcoFFUJ9yfsIsgYWHYOwniDo6NDVRyI+DI15CwrAQDcOBYP1wIAPDemTciVi3BHiFFS3ORuf32Fug69pIAuO/8mPWJP+seecxcXS4wLbxxru8LFMx3/fPv971QR1c7gZHPAIK9kQUFFVRm7g9giA+hhVFZFfLxzgBBJXpTuQoTDusjTlt+l3om8w692vpMuccZ0/CEAv6vM1P7g+vWur/e6jmi5NvA291bv3ijCRfN6wrYLbhuZx4JqT0R6T/CY/+jAKpfvl/ktqe6KNK/lQJqh9Ug9FO5+/w+lNZyOXFgIlQbijC3DgdyCK2rHlnBS67XCWDixQUYeCC/slhRo0mtkphWg+mNnJT5vq7GFEpLupl4pRfi/HK805Pzj4GjdBZXxTcHzSEwdDZRXb7puoZrmATLQo+jbAqz4UgUs3EKcjXIt66HIeaL8qr6hVDZ51Xhuk+iY9E06DijnqGZ7zIRfXFu3cbSvWwwuPCjtY1qxzlTaG1esWPMI9Mgc="
    - secure: "PIjVWtpybl0XK5MfCkxoQqzNZ9clrPpsMMd+YSKpB7HltjJ00HKXzzgEWc/fTjObI3IXUtyTFYV0u8CU38Vaudz23gVlAzzTI4YeFeeFuovKdgFV3UvNVVq0yrtBBlDMGxA3fU7Dl9P3AcVGY4nzEQV/G76FTQfC+iEvuGlzBxWOVR8q7C2bgAH3l0n2TDXJmtICDgNjFpp41eJL0DebDyS3eCD8t6Cs9mjLYIcGEYBGqe0qhX+rZ2QJZZY1n0FRAobm2hSmNjuT5isj7HGTYkFuBJY5al20T2uEOKeeO4XYQa+/wx5XkTvYC3sj6uwsK5h/xQ4ba8t69i8xbGgpN2xA+VbDVMeTCKo/SGoJH/iNx8ppyJfIIH0EzJEqnbaKiTby+KkvBGuqQyd2yBLdYDYLa1drPDuaPMWx055ykqzDf7kyRGzjgnk5xTYaJ7AqfZ22/H0RYOuOq9SnjkmbsJ5KU3Q/z8Wim6c7UT5UdaKy5ETjnWUbpwZaqZakHNfepblKejvpAOBCzNF1MYfmivKID2dqljsTBUqycrjhvIY2KTv8tRuyH3Qr7qOzDmeupwAVSlQ2woaIKyT/f3lsR5tAiUscVYcaJ9yL91aZKPCGGUKuvSjMGcjsinSMNqF2JhTa6BlSmCPVJiH5ExOYxP3taJ6GDbNUDrQhVbqGFIU="

install:
  - python --version
  - python -m pip install --upgrade pip
  - pip --version
  - pip install cryspy
  - pip install PySide2
  - pip install pyinstaller
  - pip install pytest
  - pip install pytest_mock
  - pip install pytest-cov
  - pip install pytest-qt
  - pip install coveralls

before_script:
  - python Scripts/CompilePyResource.py
  - python Scripts/CopyMissingLibs.py "$TRAVIS_OS_NAME"
  - python Scripts/MakeDist.py "$TRAVIS_OS_NAME"

#script:
  #- pytest --version
  #- if [ "$TRAVIS_OS_NAME" == osx ]; then export PYTHONPATH=.:App:App/PyImports:$PYTHONPATH; pytest --cov=App Tests; fi
  #- if [ "$TRAVIS_OS_NAME" != osx ]; then python runTests.py; fi

after_success:
  - python Scripts/MakeInstaller.py "$TRAVIS_OS_NAME"
  - python Scripts/SignCode.py "$TRAVIS_OS_NAME" "$CODE_SIGN_PSWD"
  - export RELEASE_NUMBER=$(cat App/QmlImports/easyDiffraction/Settings.qml | grep 'appVersion' | sed 's/.*"\(.*\)"[^"]*$/\1/')
  - echo $RELEASE_NUMBER
  - zip -j easyDiffraction-$TRAVIS_OS_NAME-v$RELEASE_NUMBER.zip dist/easyDiffractionInstaller*
  #- coveralls

#cache:
#  directories:
#    - ~/easyDiffraction

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Travis Builder"
  - git config --local user.email "travis@travis-ci.org"
  - export TRAVIS_TAG=v$RELEASE_NUMBER
  - '[ "$TRAVIS_BRANCH" == master ] || export TRAVIS_TAG=$TRAVIS_BRANCH-$TRAVIS_TAG'
  - export RELEASE_TITLE=easyDiffraction-$TRAVIS_TAG
  # This writes a changelog. If wanted
  #- '[ "$TRAVIS_BRANCH" != master ] || cd ../ && pip3 install gitchangelog pystache && echo "output_engine = mustache(\"markdown\")" > .gitchangelog.rc && gitchangelog ^$(git describe --abbrev=0 --tags) HEAD > CHANGELOG'

notifications:
  slack:
    rooms:
      - secure: "t0nR618a2fr2EDpyfKWBBkcf5MJ549P732EGvN9gwXVYvl4z977KSSH6uPEw7/KmMec9BhMg882hJidoeh1XgvUQOiVan4jrlvn16z2INPWh/dloXOZN5YWz87tSLR1jn1tDaKSK7gaOF5HAosPbQ2/UriUaAG9d9GHJKJzCogNDAFwFge3K/b4KJr1kYpwS5Vd5K99peWnsrNYBz1M4+Xjc49cd5t5FKULtFduX0Zb25t3dQ25u9LfGQ5lyH65UNSqcu9DP4RZmX00KLYNnIOYtzuyWvehPhisoBozA+Fpuly2IaFPVswtHqO/h9kziyYBBcnEAvG0U+KHmkJy21vDHN5+yPoHlcuAr0Q95C7GEpUT/JVAeNggxWWF4WLYrcTbZXWGt69pBhuFUAZRnbzSV+wBF5ZAOK/5W9TvxYMM1uS9AqdLEmUQdtIGrj2VIDS1na0dielNMnOhBc0Xgap2as/Kb1aEkPuSA6kENDOGXrw1Vs0VjFK3iWOlyzHbfHdHWM1/WZOO2sZRNjdTgWS5x5UXJbozTcM5mzcAkZ21vVpVG5h7LQI3cMPpD45Hmtmnko6S+7FlaknesIeXXhZPwILxN12LtbBo7AkUqtdi/w4Do7CAA++hNJRQx2txa9Mfi6R9XhNccc9+3Mto6lw5hW9mDmb2b1TlrLksW5Ew="
    on_success: always
    on_failure: always

deploy:
  # This is where I deploy the results to github
  - provider: releases
    name: $RELEASE_TITLE
    api_key:
      secure: "s3uqRW5prwmZp8dFSroXQCUBOFOCVU10iSGMVfBCtn51HDmF/RXDlQw7UJHs8vJJbtY+0tQ2yByCj5nah6VzaXKVyvxl7/VXGgB67LkHaI4idKV8HOqcSShJ1sxGapvMC3u5Ezx8tg3cK09SJnSFXq/xk9NoTdmxuFDX6X9P3jRq/CKM5mkHkOiUWLeU86sulJiBIBdcYoFwIXOKQE5KlDDBFDiI/qnEC98B4lKMSzRQB5VQEXeW+Z4f7KsK7/aS8H+Tw0sA+P81TN8CVXBeWAhBpEzrSAxLGEMRTP5GY/AkiJbdBuJMmHcc1t0S79OBsKQcrV2Yl9CtN4/WuvIH2caX19z39AvfjzDyHMnkDzN0XBv5fvQYla/45PxdmQf8O6GaiITXewBu+1DT9nQzLLaLh6GHz/zdGZeO2/ivwBMQnd8A3+B8YaO5/2dYGndAPDt06ECQBKI6RGvEBfTjApSTnuX07CjAwkXyg39uZo4KRtF1FGSjZdcNaDQGByPNHu4IOM60xDgM7VHI0EBz5YfZMpVs0sVTIsnwe7m+tFzRa00E/mlFdPCUvpYeZxgBJpNIvoBA53R7hUcvPd/xNeTfiT7tF08cAc3rdm+Mmdeewifn91SGunUBwLiNBVLB6YVlIfj2Btkce5fgdLTkVGnBlnawGAZtJwtH1Z6EJR4="
    skip_cleanup: true
    draft: false
    overwrite: true
    file_glob: true
    file: easyDiffraction-*.zip
    on:
      branch: master
  - provider: releases
    name: $RELEASE_TITLE
    api_key:
      secure: "s3uqRW5prwmZp8dFSroXQCUBOFOCVU10iSGMVfBCtn51HDmF/RXDlQw7UJHs8vJJbtY+0tQ2yByCj5nah6VzaXKVyvxl7/VXGgB67LkHaI4idKV8HOqcSShJ1sxGapvMC3u5Ezx8tg3cK09SJnSFXq/xk9NoTdmxuFDX6X9P3jRq/CKM5mkHkOiUWLeU86sulJiBIBdcYoFwIXOKQE5KlDDBFDiI/qnEC98B4lKMSzRQB5VQEXeW+Z4f7KsK7/aS8H+Tw0sA+P81TN8CVXBeWAhBpEzrSAxLGEMRTP5GY/AkiJbdBuJMmHcc1t0S79OBsKQcrV2Yl9CtN4/WuvIH2caX19z39AvfjzDyHMnkDzN0XBv5fvQYla/45PxdmQf8O6GaiITXewBu+1DT9nQzLLaLh6GHz/zdGZeO2/ivwBMQnd8A3+B8YaO5/2dYGndAPDt06ECQBKI6RGvEBfTjApSTnuX07CjAwkXyg39uZo4KRtF1FGSjZdcNaDQGByPNHu4IOM60xDgM7VHI0EBz5YfZMpVs0sVTIsnwe7m+tFzRa00E/mlFdPCUvpYeZxgBJpNIvoBA53R7hUcvPd/xNeTfiT7tF08cAc3rdm+Mmdeewifn91SGunUBwLiNBVLB6YVlIfj2Btkce5fgdLTkVGnBlnawGAZtJwtH1Z6EJR4="
    skip_cleanup: true
    draft: true
    overwrite: true
    file_glob: true
    file: easyDiffraction-*.zip
    on:
      all_branches: true
      condition: "$TRAVIS_BRANCH != 'master'"

after_deploy:
  -  |
     if [ $TRAVIS_BRANCH = "master" ]; then
        cd ~/
        git clone https://github.com/easyDiffraction/easyDiffraction.github.io.git
        cd easyDiffraction.github.io
        git remote set-url origin https://$GH_TOKEN@github.com/easyDiffraction/easyDiffraction.github.io.git
        cat index_template.html | awk '{gsub(/RELEASE_V/,"'$TRAVIS_TAG'")}1' | awk '{gsub(/RELEASE_N/,"'$RELEASE_NUMBER'")}1' | awk '{gsub(/RELEASE_D/,"'$(date +'%d %b %Y')'")}1' > index.html
        git add index.html
        git commit -m 'Bumped release links [ci skip]'
        git push origin HEAD:master
     fi
