project:
  name: easyDiffraction
  dir_path: null
  subdirs:
    distribution: Distribution
    scripts: Scripts
    certificates: Certificates
    examples: Examples
github:
  owner: easyDiffraction
  repo: easyDiffraction
os:
  name: null
pyinstaller:
  lib_path:
    cryspy: null
    shiboken2: null
    pyside2: null
  missing_files:
    osx:
    - libshiboken2.abi3.*.dylib
    windows:
    - shiboken2.abi3.dll
    - MSVCP140.dll
    linux: []
  separator:
    osx: ':'
    windows: ;
    linux: ':'
app:
  name: easyDiffraction
  organization: easyDiffraction
  url: https://easydiffraction.org
icon:
  ext:
    osx: icns
    windows: ico
    linux: png
release:
  version: 0.3.7
  date: 19 Nov 2019
  changes: # Get from pull requests description?
  - Minor Changes 1
  - Minor Changes 2
