# encoding: UTF-8

from objectmaphelper import *

easyDiffraction_QQuickApplicationWindow = {"title": "easyDiffraction", "type": "QQuickApplicationWindow", "unnamed": 1, "visible": True}
easyDiffraction_Overlay = {"container": easyDiffraction_QQuickApplicationWindow, "type": "Overlay", "unnamed": 1, "visible": True}
modelling_Button = {"checkable": True, "container": easyDiffraction_Overlay, "id": "modellingButton", "text": "Modelling", "type": "Button", "unnamed": 1, "visible": True}
analysis_Button = {"checkable": True, "container": easyDiffraction_Overlay, "id": "analysisButton", "text": "Analysis", "type": "Button", "unnamed": 1, "visible": True}
label_MnemonicLabel = {"container": easyDiffraction_Overlay, "objectName": "label", "type": "MnemonicLabel", "visible": True}
label_MnemonicLabel_2 = {"container": easyDiffraction_Overlay, "objectName": "label", "occurrence": 2, "type": "MnemonicLabel", "visible": True}
next_Text = {"container": easyDiffraction_Overlay, "text": "Next", "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_Next_step_Experimental_Data_Button = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "text": "Next step: Experimental Data", "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_topChart_QtCharts_DeclarativeChart = {"container": easyDiffraction_QQuickApplicationWindow, "id": "topChart", "type": "QtCharts::DeclarativeChart", "unnamed": 1, "visible": True}
fadeOut_Rectangle = {"container": easyDiffraction_Overlay, "id": "fadeOut", "type": "Rectangle", "unnamed": 1, "visible": True}
easyDiffraction_label_MnemonicLabel = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "label", "occurrence": 16, "type": "MnemonicLabel", "visible": True}
easyDiffraction_label_MnemonicLabel_2 = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "label", "occurrence": 19, "type": "MnemonicLabel", "visible": True}
easyDiffraction_label_MnemonicLabel_3 = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "label", "occurrence": 15, "type": "MnemonicLabel", "visible": True}
easyDiffraction_label_MnemonicLabel_4 = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "label", "occurrence": 18, "type": "MnemonicLabel", "visible": True}
easyDiffraction_Image = {"container": easyDiffraction_QQuickApplicationWindow, "source": "qrc:Qml/Imports/easyDiffraction/Resources/Examples/CeCuAl3_POLARIS/cecual.png", "type": "Image", "unnamed": 1, "visible": True}
easyDiffraction_tabBar_TabBar = {"container": easyDiffraction_QQuickApplicationWindow, "id": "tabBar", "occurrence": 2, "type": "TabBar", "unnamed": 1, "visible": True}
tabBar_tabBar_TabBar = {"container": easyDiffraction_tabBar_TabBar, "id": "tabBar", "type": "TabBar", "unnamed": 1, "visible": True}
tabBar_label_MnemonicLabel = {"container": tabBar_tabBar_TabBar, "objectName": "label", "occurrence": 2, "type": "MnemonicLabel", "visible": True}
easyDiffraction_Text = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 38, "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_image_IconImage = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "image", "source": "qrc:Qml/Imports/easyAnalysis/Resources/Fonts/Awesome/svgs/plus-circle.svg", "type": "IconImage", "visible": True}
easyDiffraction_Text_2 = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 7, "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_Rectangle = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 214, "type": "Rectangle", "unnamed": 1, "visible": True}
easyDiffraction_Text_3 = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 16, "type": "Text", "unnamed": 1, "visible": True}
click_here_to_add_or_import_a_new_instrument_Text = {"container": easyDiffraction_Overlay, "text": "Click here to add or import a new instrument.", "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_Text_4 = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 25, "type": "Text", "unnamed": 1, "visible": True}
click_here_to_add_or_import_a_new_phase_Text = {"container": easyDiffraction_Overlay, "text": "Click here to add or import a new phase.", "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_tabbar_TabBar = {"container": easyDiffraction_QQuickApplicationWindow, "id": "tabbar", "type": "TabBar", "unnamed": 1, "visible": True}
tabbar_label_MnemonicLabel = {"container": easyDiffraction_tabbar_TabBar, "objectName": "label", "occurrence": 2, "type": "MnemonicLabel", "visible": True}
easyDiffraction_Display_coordinate_system_CheckBox = {"checkable": True, "container": easyDiffraction_QQuickApplicationWindow, "text": "Display coordinate system", "type": "CheckBox", "unnamed": 1, "visible": True}
tabbar_label_MnemonicLabel_2 = {"container": easyDiffraction_tabbar_TabBar, "objectName": "label", "type": "MnemonicLabel", "visible": True}
easyDiffraction_Rectangle_2 = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 149, "type": "Rectangle", "unnamed": 1, "visible": True}
easyDiffraction_image_IconImage_2 = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "image", "source": "qrc:Qml/Imports/easyAnalysis/Resources/Fonts/Awesome/svgs/play-circle.svg", "type": "IconImage", "visible": True}
easyDiffraction_Slider = {"container": easyDiffraction_QQuickApplicationWindow, "type": "Slider", "unnamed": 1, "visible": True}
easyDiffraction_Next_step_Summary_Button = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "text": "Next step: Summary", "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_Text_5 = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 23, "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_Rectangle_3 = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 169, "type": "Rectangle", "unnamed": 1, "visible": True}
prev_Text = {"container": easyDiffraction_Overlay, "text": "Prev", "type": "Text", "unnamed": 1, "visible": True}
click_here_to_add_or_import_new_data_Text = {"container": easyDiffraction_Overlay, "text": "Click here to add or import new data.", "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_Overlay_2 = {"container": easyDiffraction_QQuickApplicationWindow, "type": "Overlay", "unnamed": 1, "visible": False}
easyDiffraction_tabBar_TabBar_2 = {"container": easyDiffraction_QQuickApplicationWindow, "id": "tabBar", "type": "TabBar", "unnamed": 1, "visible": True}
tabBar_Instrument_Model_Button = {"checkable": True, "container": easyDiffraction_tabBar_TabBar_2, "text": "Instrument Model", "type": "Button", "unnamed": 1, "visible": True}
tabBar_Experimental_Data_Button = {"checkable": True, "container": easyDiffraction_tabBar_TabBar_2, "text": "Experimental Data", "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_image_IconImage_3 = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "image", "source": "qrc:Qml/Imports/easyAnalysis/Resources/Fonts/Awesome/svgs/bug.svg", "type": "IconImage", "visible": True}
easyDiffraction_Program_Preferences_Button = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "id": "titleArea", "text": "Program Preferences", "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_Show_Animated_Intro_CheckBox = {"checkable": True, "container": easyDiffraction_QQuickApplicationWindow, "text": "Show Animated Intro", "type": "CheckBox", "unnamed": 1, "visible": True}
appIcon_Image = {"container": easyDiffraction_Overlay, "id": "appIcon", "source": "qrc:Qml/Imports/easyDiffraction/Resources/Icons/App.svg", "type": "Image", "unnamed": 1, "visible": True}
easyDiffraction_Open_another_project_Button = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "text": "Open another project", "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_image_IconImage_4 = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "occurrence": 17, "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_Text_6 = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 15, "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_Button = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "occurrence": 17, "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_Button_2 = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "occurrence": 18, "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_Text_7 = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 2, "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_image_IconImage_5 = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "image", "source": "file::/Imports/easyAnalysis/Resources/Fonts/Awesome/svgs/file-upload.svg", "type": "IconImage", "visible": True}
easyDiffraction_Fe3O4_Text = {"container": easyDiffraction_QQuickApplicationWindow, "text": "Fe3O4", "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_label_MnemonicLabel_5 = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "label", "occurrence": 20, "type": "MnemonicLabel", "visible": True}
easyDiffraction_chart_QtDataVisualization_DeclarativeScatter = {"container": easyDiffraction_QQuickApplicationWindow, "id": "chart", "type": "QtDataVisualization::DeclarativeScatter", "unnamed": 1, "visible": True}
easyDiffraction_StackLayout = {"container": easyDiffraction_QQuickApplicationWindow, "type": "StackLayout", "unnamed": 1, "visible": True}
easyDiffraction_ColumnLayout = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 2, "type": "ColumnLayout", "unnamed": 1, "visible": True}
easyDiffraction_ApplicationWindow_ContentItem = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "ApplicationWindow", "type": "ContentItem", "visible": True}
easyDiffraction_label_MnemonicLabel_6 = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "label", "occurrence": 14, "type": "MnemonicLabel", "visible": True}
tabBar_Home_Button = {"checkable": True, "container": easyDiffraction_tabBar_TabBar_2, "text": "Home", "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_Experimental_Data_Button = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "text": "Experimental Data", "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_label_MnemonicLabel_7 = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "label", "occurrence": 22, "type": "MnemonicLabel", "visible": True}
easyDiffraction_contentListView_ListView = {"container": easyDiffraction_QQuickApplicationWindow, "id": "contentListView", "type": "ListView", "unnamed": 1, "visible": True}
contentListView_contentRow_Rectangle = {"container": easyDiffraction_contentListView_ListView, "id": "contentRow", "index": 0, "type": "Rectangle", "unnamed": 1, "visible": True}
contentRow_CheckBox = {"checkable": True, "container": contentListView_contentRow_Rectangle, "type": "CheckBox", "unnamed": 1, "visible": True}
easyDiffraction_Start_fitting_Button = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "id": "pausePlayButton", "text": "Start fitting", "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_Show_User_Guides_CheckBox = {"checkable": True, "container": easyDiffraction_QQuickApplicationWindow, "text": "Show User Guides", "type": "CheckBox", "unnamed": 1, "visible": True}
easyDiffraction_headerTableView_TableView = {"container": easyDiffraction_QQuickApplicationWindow, "id": "headerTableView", "type": "TableView", "unnamed": 1, "visible": True}
headerTableView_x_Text = {"container": easyDiffraction_headerTableView_TableView, "text": "x", "type": "Text", "unnamed": 1, "visible": True}
headerTableView_y_obs_up_Text = {"container": easyDiffraction_headerTableView_TableView, "occurrence": 2, "text": "y_obs_up", "type": "Text", "unnamed": 1, "visible": True}
headerTableView_sy_obs_up_Text = {"container": easyDiffraction_headerTableView_TableView, "text": "sy_obs_up", "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_contentTableView_TableView = {"container": easyDiffraction_QQuickApplicationWindow, "id": "contentTableView", "type": "TableView", "unnamed": 1, "visible": True}
contentTableView_TextInput = {"backgroundcolor": "#ffffff", "container": easyDiffraction_contentTableView_TableView, "echoMode": 0, "occurrence": 8, "type": "TextInput", "unnamed": 1, "visible": True}
tabBar_Text_View_TabButton = {"checkable": True, "container": tabBar_tabBar_TabBar, "text": "Text View", "type": "TabButton", "unnamed": 1, "visible": True}
tabBar_Plot_View_TabButton = {"checkable": True, "container": tabBar_tabBar_TabBar, "text": "Plot View", "type": "TabButton", "unnamed": 1, "visible": True}
easyDiffraction_Text_8 = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 35, "type": "Text", "unnamed": 1, "visible": True}
tabBar_Structure_View_TabButton = {"checkable": True, "container": tabBar_tabBar_TabBar, "text": "Structure View", "type": "TabButton", "unnamed": 1, "visible": True}
easyDiffraction_image_IconImage_6 = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "id": "titleArea", "text": "Symmetry and cell parameters", "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_ColumnLayout_2 = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 8, "type": "ColumnLayout", "unnamed": 1, "visible": True}
easyDiffraction_image_IconImage_7 = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "id": "titleArea", "text": "Symmetry and cell parameters", "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_TextField = {"backgroundcolor": "#00000000", "container": easyDiffraction_QQuickApplicationWindow, "echoMode": 0, "type": "TextField", "unnamed": 1, "visible": True}
easyDiffraction_TextField_2 = {"backgroundcolor": "#00000000", "container": easyDiffraction_QQuickApplicationWindow, "echoMode": 0, "occurrence": 2, "type": "TextField", "unnamed": 1, "visible": True}
easyDiffraction_TextField_3 = {"backgroundcolor": "#00000000", "container": easyDiffraction_QQuickApplicationWindow, "echoMode": 0, "occurrence": 3, "type": "TextField", "unnamed": 1, "visible": True}
easyDiffraction_contentListView_ListView_2 = {"container": easyDiffraction_QQuickApplicationWindow, "id": "contentListView", "occurrence": 2, "type": "ListView", "unnamed": 1, "visible": True}
contentListView_contentRow_Rectangle_2 = {"container": easyDiffraction_contentListView_ListView_2, "id": "contentRow", "index": 0, "type": "Rectangle", "unnamed": 1, "visible": True}
contentRow_90_0000_Text_2 = {"container": contentListView_contentRow_Rectangle_2, "occurrence": 3, "text": "90.0000", "type": "Text", "unnamed": 1, "visible": True}
contentRow_90_0000_Text = {"container": contentListView_contentRow_Rectangle_2, "text": "90.0000", "type": "Text", "unnamed": 1, "visible": True}
contentRow_8_5500_Text_3 = {"container": contentListView_contentRow_Rectangle_2, "occurrence": 3, "text": "8.5500", "type": "Text", "unnamed": 1, "visible": True}
contentRow_8_5500_Text_2 = {"container": contentListView_contentRow_Rectangle_2, "occurrence": 2, "text": "8.5500", "type": "Text", "unnamed": 1, "visible": True}
contentRow_8_5500_Text = {"container": contentListView_contentRow_Rectangle_2, "text": "8.5500", "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_image_IconImage_8 = {"container": easyDiffraction_QQuickApplicationWindow, "id": "group1", "title": "Symmetry and cell parameters", "type": "GroupBox", "unnamed": 1, "visible": True}
easyDiffraction_image_IconImage_9 = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "id": "titleArea", "text": "Atoms, atomic coordinates and occupations", "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_contentListView_ListView_3 = {"container": easyDiffraction_QQuickApplicationWindow, "id": "contentListView", "occurrence": 3, "type": "ListView", "unnamed": 1, "visible": True}
easyDiffraction_Color_Text = {"container": easyDiffraction_QQuickApplicationWindow, "text": "Color", "type": "Text", "unnamed": 1, "visible": True}
contentListView_contentRow_Rectangle_3 = {"container": easyDiffraction_contentListView_ListView_3, "id": "contentRow", "index": 0, "type": "Rectangle", "unnamed": 1, "visible": True}
contentRow_button_Button = {"checkable": False, "container": contentListView_contentRow_Rectangle_3, "id": "button", "type": "Button", "unnamed": 1, "visible": True}
contentListView_contentRow_Rectangle_5 = {"container": easyDiffraction_contentListView_ListView_3, "id": "contentRow", "index": 2, "type": "Rectangle", "unnamed": 1, "visible": True}
contentRow_Rectangle = {"container": contentListView_contentRow_Rectangle_5, "type": "Rectangle", "unnamed": 1, "visible": True}
contentRow_O1_Text = {"container": contentListView_contentRow_Rectangle_5, "text": "O1", "type": "Text", "unnamed": 1, "visible": True}
contentListView_contentRow_Rectangle_4 = {"container": easyDiffraction_contentListView_ListView_3, "id": "contentRow", "index": 1, "type": "Rectangle", "unnamed": 1, "visible": True}
contentRow_Fe3B_Text = {"container": contentListView_contentRow_Rectangle_4, "text": "Fe3B", "type": "Text", "unnamed": 1, "visible": True}
contentRow_Fe3A_Text = {"container": contentListView_contentRow_Rectangle_3, "text": "Fe3A", "type": "Text", "unnamed": 1, "visible": True}
contentRow_1_0000_Text = {"container": contentListView_contentRow_Rectangle_5, "text": "1.0000", "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_Remove_all_atoms_Button = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "text": "Remove all atoms", "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_Add_new_atom_Button = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "text": "Add new atom", "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_contentListView_ListView_4 = {"container": easyDiffraction_QQuickApplicationWindow, "id": "contentListView", "occurrence": 4, "type": "ListView", "unnamed": 1, "visible": True}
easyDiffraction_Uiso_Text = {"container": easyDiffraction_QQuickApplicationWindow, "text": "Uiso", "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_U23_Text = {"container": easyDiffraction_QQuickApplicationWindow, "text": "U23", "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_U11_Text = {"container": easyDiffraction_QQuickApplicationWindow, "text": "U11", "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_Type_Text = {"container": easyDiffraction_QQuickApplicationWindow, "text": "Type", "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_Label_Text = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 3, "text": "Label", "type": "Text", "unnamed": 1, "visible": True}
contentListView_contentRow_Rectangle_6 = {"container": easyDiffraction_contentListView_ListView_4, "id": "contentRow", "index": 0, "type": "Rectangle", "unnamed": 1, "visible": True}
contentRow_uani_Text = {"container": contentListView_contentRow_Rectangle_6, "text": "uani", "type": "Text", "unnamed": 1, "visible": True}
contentListView_contentRow_Rectangle_7 = {"container": easyDiffraction_contentListView_ListView_4, "id": "contentRow", "index": 2, "type": "Rectangle", "unnamed": 1, "visible": True}
contentRow_Text_2 = {"container": contentListView_contentRow_Rectangle_7, "occurrence": 10, "type": "Text", "unnamed": 1, "visible": True}
contentRow_Text = {"container": contentListView_contentRow_Rectangle_7, "occurrence": 5, "type": "Text", "unnamed": 1, "visible": True}
contentRow_O1_Text_2 = {"container": contentListView_contentRow_Rectangle_7, "text": "O1", "type": "Text", "unnamed": 1, "visible": True}
contentRow_Fe3A_Text_2 = {"container": contentListView_contentRow_Rectangle_6, "text": "Fe3A", "type": "Text", "unnamed": 1, "visible": True}
contentRow_1_Text = {"container": contentListView_contentRow_Rectangle_6, "text": 1, "type": "Text", "unnamed": 1, "visible": True}
contentRow_0_0000_Text_2 = {"container": contentListView_contentRow_Rectangle_7, "text": "0.0000", "type": "Text", "unnamed": 1, "visible": True}
contentRow_0_0000_Text = {"container": contentListView_contentRow_Rectangle_6, "occurrence": 7, "text": "0.0000", "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_image_IconImage_10 = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "image", "occurrence": 4, "source": "C:/util/easyDiffraction/easyDiffraction/QmlImports/easyAnalysis/Resources/Icons/triangle-right.svg", "type": "IconImage", "visible": True}
easyDiffraction_iso_Text = {"container": easyDiffraction_QQuickApplicationWindow, "text": "χiso", "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_contentListView_ListView_5 = {"container": easyDiffraction_QQuickApplicationWindow, "id": "contentListView", "occurrence": 5, "type": "ListView", "unnamed": 1, "visible": True}
easyDiffraction_23_Text = {"container": easyDiffraction_QQuickApplicationWindow, "text": "χ23", "type": "Text", "unnamed": 1, "visible": True}
contentListView_contentRow_Rectangle_9 = {"container": easyDiffraction_contentListView_ListView_5, "id": "contentRow", "index": 2, "type": "Rectangle", "unnamed": 1, "visible": True}
contentRow_Text_5 = {"container": contentListView_contentRow_Rectangle_9, "occurrence": 10, "type": "Text", "unnamed": 1, "visible": True}
contentRow_Text_4 = {"container": contentListView_contentRow_Rectangle_9, "occurrence": 5, "type": "Text", "unnamed": 1, "visible": True}
contentListView_contentRow_Rectangle_8 = {"container": easyDiffraction_contentListView_ListView_5, "id": "contentRow", "index": 1, "type": "Rectangle", "unnamed": 1, "visible": True}
contentRow_Text_3 = {"container": contentListView_contentRow_Rectangle_8, "occurrence": 4, "type": "Text", "unnamed": 1, "visible": True}
contentRow_O1_Text_3 = {"container": contentListView_contentRow_Rectangle_9, "text": "O1", "type": "Text", "unnamed": 1, "visible": True}
contentRow_2_Text = {"container": contentListView_contentRow_Rectangle_8, "text": 2, "type": "Text", "unnamed": 1, "visible": True}
contentRow_0_0000_Text_3 = {"container": contentListView_contentRow_Rectangle_8, "occurrence": 3, "text": "0.0000", "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_bottomChart_QtCharts_DeclarativeChart = {"container": easyDiffraction_QQuickApplicationWindow, "id": "bottomChart", "type": "QtCharts::DeclarativeChart", "unnamed": 1, "visible": True}
contentRow_qwe_TextInput = {"backgroundcolor": "#2a99d9", "container": contentListView_contentRow_Rectangle, "echoMode": 0, "id": "qwe", "type": "TextInput", "unnamed": 1, "visible": True}
easyDiffraction_sliderHandle_Rectangle = {"container": easyDiffraction_QQuickApplicationWindow, "id": "sliderHandle", "type": "Rectangle", "unnamed": 1, "visible": True}
contentListView_contentRow_Rectangle_12 = {"container": easyDiffraction_contentListView_ListView, "id": "contentRow", "index": 24, "type": "Rectangle", "unnamed": 1, "visible": True}
contentRow_CheckBox_4 = {"checkable": True, "container": contentListView_contentRow_Rectangle_12, "type": "CheckBox", "unnamed": 1, "visible": True}
contentListView_contentRow_Rectangle_11 = {"container": easyDiffraction_contentListView_ListView, "id": "contentRow", "index": 17, "type": "Rectangle", "unnamed": 1, "visible": True}
contentRow_CheckBox_3 = {"checkable": True, "container": contentListView_contentRow_Rectangle_11, "type": "CheckBox", "unnamed": 1, "visible": True}
contentListView_contentRow_Rectangle_10 = {"container": easyDiffraction_contentListView_ListView, "id": "contentRow", "index": 8, "type": "Rectangle", "unnamed": 1, "visible": True}
contentRow_CheckBox_2 = {"checkable": True, "container": contentListView_contentRow_Rectangle_10, "type": "CheckBox", "unnamed": 1, "visible": True}
contentListView_Rectangle = {"container": contentListView_contentRow_Rectangle_12, "occurrence": 3, "type": "Text", "unnamed": 1, "visible": True}
contentRow_Text_9 = {"container": contentListView_contentRow_Rectangle_12, "occurrence": 3, "type": "Text", "unnamed": 1, "visible": True}
contentListView_contentRow_Rectangle_13 = {"container": easyDiffraction_contentListView_ListView, "id": "contentRow", "index": 1, "type": "Rectangle", "unnamed": 1, "visible": True}
contentRow_Text_8 = {"container": contentListView_contentRow_Rectangle_13, "occurrence": 3, "type": "Text", "unnamed": 1, "visible": True}
contentRow_Text_7 = {"container": contentListView_contentRow_Rectangle_10, "occurrence": 3, "type": "Text", "unnamed": 1, "visible": True}
contentListView_contentRow_Rectangle_14 = {"container": easyDiffraction_contentListView_ListView, "id": "contentRow", "index": 18, "type": "Rectangle", "unnamed": 1, "visible": True}
contentRow_Text_6 = {"container": contentListView_contentRow_Rectangle_14, "occurrence": 3, "type": "Text", "unnamed": 1, "visible": True}
contentListView_Rectangle_2 = {"container": easyDiffraction_contentListView_ListView, "type": "ScrollBar", "unnamed": 1, "visible": True}
easyDiffraction_label_MnemonicLabel_8 = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "label", "occurrence": 11, "type": "MnemonicLabel", "visible": True}
o_Rectangle = {"container": easyDiffraction_Overlay, "occurrence": 2, "type": "Rectangle", "unnamed": 1, "visible": True}
optimization_terminated_successfully_Number_of_evaluations_of_the_objective_functions_120_Number_of_iterations_performed_by_the_optimizer_15_Final_goodnes_of_fit_3_00_Label = {"container": easyDiffraction_Overlay, "text": "Optimization terminated successfully.\nNumber of evaluations of the objective functions: 120\nNumber of iterations performed by the optimizer: 15\nFinal goodness-of-fit (χ²): 3.00", "type": "Label", "unnamed": 1, "visible": True}
o_Rectangle_2 = {"container": easyDiffraction_Overlay, "type": "Rectangle", "unnamed": 1, "visible": True}
contentRow_qwe_TextInput_2 = {"backgroundcolor": "#ffffff", "container": contentListView_contentRow_Rectangle_10, "echoMode": 0, "id": "qwe", "type": "TextInput", "unnamed": 1, "visible": True}
contentRow_0_0008_Text = {"container": contentListView_contentRow_Rectangle, "text": "0.0008", "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_Text_9 = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 92, "type": "Text", "unnamed": 1, "visible": True}
tabBar_Report_TabButton = {"checkable": True, "container": tabBar_tabBar_TabBar, "text": "Report", "type": "TabButton", "unnamed": 1, "visible": True}
easyDiffraction_textArea_TextArea = {"container": easyDiffraction_QQuickApplicationWindow, "id": "textArea", "type": "TextArea", "unnamed": 1, "visible": True}
easyDiffraction_exportFileExt_ComboBox = {"container": easyDiffraction_QQuickApplicationWindow, "id": "exportFileExt", "type": "ComboBox", "unnamed": 1, "visible": True}
easyDiffraction_Export_as_GroupBox = {"container": easyDiffraction_QQuickApplicationWindow, "title": "Export as...", "type": "GroupBox", "unnamed": 1, "visible": True}
easyDiffraction_Export_Button = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "id": "exportButton", "text": "Export", "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_image_IconImage_11 = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "image", "source": "C:/util/easyDiffraction/easyDiffraction/QmlImports/easyAnalysis/Resources/Fonts/Awesome/svgs/arrow-circle-right.svg", "type": "IconImage", "visible": True}
tabBar_label_MnemonicLabel_2 = {"container": easyDiffraction_tabBar_TabBar_2, "objectName": "label", "type": "MnemonicLabel", "visible": True}
easyDiffraction_Text_10 = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 136, "type": "Text", "unnamed": 1, "visible": True}
contentRow_ColorImage = {"container": contentListView_contentRow_Rectangle, "source": "qrc:/qt-project.org/imports/QtQuick/Controls.2/images/check.png", "type": "ColorImage", "unnamed": 1, "visible": True}
contentRow_ColorImage_2 = {"container": contentListView_contentRow_Rectangle_10, "source": "qrc:/qt-project.org/imports/QtQuick/Controls.2/images/check.png", "type": "ColorImage", "unnamed": 1, "visible": True}
contentListView_Rectangle_3 = {"container": easyDiffraction_contentListView_ListView, "index": 0, "occurrence": 2, "type": "Rectangle", "unnamed": 1, "visible": True}
contentRow_ColorImage_3 = {"container": contentListView_contentRow_Rectangle_11, "source": "qrc:/qt-project.org/imports/QtQuick/Controls.2/images/check.png", "type": "ColorImage", "unnamed": 1, "visible": True}
contentRow_ColorImage_4 = {"container": contentListView_contentRow_Rectangle_12, "source": "qrc:/qt-project.org/imports/QtQuick/Controls.2/images/check.png", "type": "ColorImage", "unnamed": 1, "visible": True}
unknow_problems_during_refinement_Label = {"container": easyDiffraction_Overlay, "text": "Unknow problems during refinement", "type": "Label", "unnamed": 1, "visible": True}
