# encoding: UTF-8

from objectmaphelper import *

easyDiffraction_QQuickApplicationWindow = {"title": "easyDiffraction", "type": "QQuickApplicationWindow", "unnamed": 1, "visible": True}
easyDiffraction_Overlay = {"container": easyDiffraction_QQuickApplicationWindow, "type": "Overlay", "unnamed": 1, "visible": True}
modelling_Button = {"checkable": True, "container": easyDiffraction_Overlay, "id": "modellingButton", "text": "Modelling", "type": "Button", "unnamed": 1, "visible": True}
analysis_Button = {"checkable": True, "container": easyDiffraction_Overlay, "id": "analysisButton", "text": "Analysis", "type": "Button", "unnamed": 1, "visible": True}
label_MnemonicLabel = {"container": easyDiffraction_Overlay, "objectName": "label", "type": "MnemonicLabel", "visible": True}
label_MnemonicLabel_2 = {"container": easyDiffraction_Overlay, "objectName": "label", "occurrence": 2, "type": "MnemonicLabel", "visible": True}
next_Text = {"container": easyDiffraction_Overlay, "text": "Next", "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_Next_step_Experimental_Data_Button = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "text": "Next step: Experimental Data", "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_topChart_QtCharts_DeclarativeChart = {"container": easyDiffraction_QQuickApplicationWindow, "id": "topChart", "type": "QtCharts::DeclarativeChart", "unnamed": 1, "visible": True}
fadeOut_Rectangle = {"container": easyDiffraction_Overlay, "id": "fadeOut", "type": "Rectangle", "unnamed": 1, "visible": True}
easyDiffraction_label_MnemonicLabel = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "label", "occurrence": 16, "type": "MnemonicLabel", "visible": True}
easyDiffraction_label_MnemonicLabel_2 = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "label", "occurrence": 19, "type": "MnemonicLabel", "visible": True}
easyDiffraction_label_MnemonicLabel_3 = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "label", "occurrence": 15, "type": "MnemonicLabel", "visible": True}
easyDiffraction_label_MnemonicLabel_4 = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "label", "occurrence": 18, "type": "MnemonicLabel", "visible": True}
easyDiffraction_Image = {"container": easyDiffraction_QQuickApplicationWindow, "source": "qrc:Qml/Imports/easyDiffraction/Resources/Examples/CeCuAl3_POLARIS/cecual.png", "type": "Image", "unnamed": 1, "visible": True}
easyDiffraction_tabBar_TabBar = {"container": easyDiffraction_QQuickApplicationWindow, "id": "tabBar", "occurrence": 2, "type": "TabBar", "unnamed": 1, "visible": True}
tabBar_tabBar_TabBar = {"container": easyDiffraction_tabBar_TabBar, "id": "tabBar", "type": "TabBar", "unnamed": 1, "visible": True}
tabBar_label_MnemonicLabel = {"container": tabBar_tabBar_TabBar, "objectName": "label", "occurrence": 2, "type": "MnemonicLabel", "visible": True}
easyDiffraction_Text = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 38, "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_image_IconImage = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "image", "source": "qrc:Qml/Imports/easyAnalysis/Resources/Fonts/Awesome/svgs/plus-circle.svg", "type": "IconImage", "visible": True}
easyDiffraction_Text_2 = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 7, "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_Rectangle = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 214, "type": "Rectangle", "unnamed": 1, "visible": True}
easyDiffraction_Text_3 = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 16, "type": "Text", "unnamed": 1, "visible": True}
click_here_to_add_or_import_a_new_instrument_Text = {"container": easyDiffraction_Overlay, "text": "Click here to add or import a new instrument.", "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_Text_4 = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 25, "type": "Text", "unnamed": 1, "visible": True}
click_here_to_add_or_import_a_new_phase_Text = {"container": easyDiffraction_Overlay, "text": "Click here to add or import a new phase.", "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_tabbar_TabBar = {"container": easyDiffraction_QQuickApplicationWindow, "id": "tabbar", "type": "TabBar", "unnamed": 1, "visible": True}
tabbar_label_MnemonicLabel = {"container": easyDiffraction_tabbar_TabBar, "objectName": "label", "occurrence": 2, "type": "MnemonicLabel", "visible": True}
easyDiffraction_Display_coordinate_system_CheckBox = {"checkable": True, "container": easyDiffraction_QQuickApplicationWindow, "text": "Display coordinate system", "type": "CheckBox", "unnamed": 1, "visible": True}
tabbar_label_MnemonicLabel_2 = {"container": easyDiffraction_tabbar_TabBar, "objectName": "label", "type": "MnemonicLabel", "visible": True}
easyDiffraction_Rectangle_2 = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 149, "type": "Rectangle", "unnamed": 1, "visible": True}
easyDiffraction_image_IconImage_2 = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "image", "source": "qrc:Qml/Imports/easyAnalysis/Resources/Fonts/Awesome/svgs/play-circle.svg", "type": "IconImage", "visible": True}
easyDiffraction_Slider = {"container": easyDiffraction_QQuickApplicationWindow, "type": "Slider", "unnamed": 1, "visible": True}
easyDiffraction_Next_step_Summary_Button = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "text": "Next step: Summary", "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_Text_5 = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 23, "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_Rectangle_3 = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 169, "type": "Rectangle", "unnamed": 1, "visible": True}
prev_Text = {"container": easyDiffraction_Overlay, "text": "Prev", "type": "Text", "unnamed": 1, "visible": True}
click_here_to_add_or_import_new_data_Text = {"container": easyDiffraction_Overlay, "text": "Click here to add or import new data.", "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_Overlay_2 = {"container": easyDiffraction_QQuickApplicationWindow, "type": "Overlay", "unnamed": 1, "visible": False}
easyDiffraction_tabBar_TabBar_2 = {"container": easyDiffraction_QQuickApplicationWindow, "id": "tabBar", "type": "TabBar", "unnamed": 1, "visible": True}
tabBar_Instrument_Model_Button = {"checkable": True, "container": easyDiffraction_tabBar_TabBar_2, "text": "Instrument Model", "type": "Button", "unnamed": 1, "visible": True}
tabBar_Experimental_Data_Button = {"checkable": True, "container": easyDiffraction_tabBar_TabBar_2, "text": "Experimental Data", "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_image_IconImage_3 = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "image", "source": "qrc:Qml/Imports/easyAnalysis/Resources/Fonts/Awesome/svgs/bug.svg", "type": "IconImage", "visible": True}
easyDiffraction_Program_Preferences_Button = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "id": "titleArea", "text": "Program Preferences", "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_Show_Animated_Intro_CheckBox = {"checkable": True, "container": easyDiffraction_QQuickApplicationWindow, "text": "Show Animated Intro", "type": "CheckBox", "unnamed": 1, "visible": True}
appIcon_Image = {"container": easyDiffraction_Overlay, "id": "appIcon", "source": "qrc:Qml/Imports/easyDiffraction/Resources/Icons/App.svg", "type": "Image", "unnamed": 1, "visible": True}
easyDiffraction_Open_another_project_Button = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "text": "Open another project", "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_image_IconImage_4 = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "image", "source": "file::/Imports/easyAnalysis/Resources/Fonts/Awesome/svgs/bug.svg", "type": "IconImage", "visible": True}
easyDiffraction_Text_6 = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 15, "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_Button = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "occurrence": 17, "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_Button_2 = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "occurrence": 18, "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_Text_7 = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 2, "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_image_IconImage_5 = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "image", "source": "file::/Imports/easyAnalysis/Resources/Fonts/Awesome/svgs/file-upload.svg", "type": "IconImage", "visible": True}
easyDiffraction_Fe3O4_Text = {"container": easyDiffraction_QQuickApplicationWindow, "text": "Fe3O4", "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_label_MnemonicLabel_5 = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "label", "occurrence": 20, "type": "MnemonicLabel", "visible": True}
easyDiffraction_chart_QtDataVisualization_DeclarativeScatter = {"container": easyDiffraction_QQuickApplicationWindow, "id": "chart", "type": "QtDataVisualization::DeclarativeScatter", "unnamed": 1, "visible": True}
easyDiffraction_StackLayout = {"container": easyDiffraction_QQuickApplicationWindow, "type": "StackLayout", "unnamed": 1, "visible": True}
easyDiffraction_ColumnLayout = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 2, "type": "ColumnLayout", "unnamed": 1, "visible": True}
easyDiffraction_ApplicationWindow_ContentItem = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "ApplicationWindow", "type": "ContentItem", "visible": True}
easyDiffraction_label_MnemonicLabel_6 = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "label", "occurrence": 14, "type": "MnemonicLabel", "visible": True}
tabBar_Home_Button = {"checkable": True, "container": easyDiffraction_tabBar_TabBar_2, "text": "Home", "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_Experimental_Data_Button = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "text": "Experimental Data", "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_label_MnemonicLabel_7 = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "label", "occurrence": 22, "type": "MnemonicLabel", "visible": True}
easyDiffraction_contentListView_ListView = {"container": easyDiffraction_QQuickApplicationWindow, "id": "contentListView", "type": "ListView", "unnamed": 1, "visible": True}
contentListView_contentRow_Rectangle = {"container": easyDiffraction_contentListView_ListView, "id": "contentRow", "index": 0, "type": "Rectangle", "unnamed": 1, "visible": True}
contentRow_CheckBox = {"checkable": True, "container": contentListView_contentRow_Rectangle, "type": "CheckBox", "unnamed": 1, "visible": True}
easyDiffraction_Start_fitting_Button = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "id": "pausePlayButton", "text": "Start fitting", "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_Show_User_Guides_CheckBox = {"checkable": True, "container": easyDiffraction_QQuickApplicationWindow, "text": "Show User Guides", "type": "CheckBox", "unnamed": 1, "visible": True}
easyDiffraction_headerTableView_TableView = {"container": easyDiffraction_QQuickApplicationWindow, "id": "headerTableView", "type": "TableView", "unnamed": 1, "visible": True}
headerTableView_x_Text = {"container": easyDiffraction_headerTableView_TableView, "text": "x", "type": "Text", "unnamed": 1, "visible": True}
headerTableView_y_obs_up_Text = {"container": easyDiffraction_headerTableView_TableView, "occurrence": 2, "text": "y_obs_up", "type": "Text", "unnamed": 1, "visible": True}
headerTableView_sy_obs_up_Text = {"container": easyDiffraction_headerTableView_TableView, "text": "sy_obs_up", "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_contentTableView_TableView = {"container": easyDiffraction_QQuickApplicationWindow, "id": "contentTableView", "type": "TableView", "unnamed": 1, "visible": True}
contentTableView_TextInput = {"backgroundcolor": "#ffffff", "container": easyDiffraction_contentTableView_TableView, "echoMode": 0, "occurrence": 8, "type": "TextInput", "unnamed": 1, "visible": True}
tabBar_Text_View_TabButton = {"checkable": True, "container": tabBar_tabBar_TabBar, "text": "Text View", "type": "TabButton", "unnamed": 1, "visible": True}
tabBar_Plot_View_TabButton = {"checkable": True, "container": tabBar_tabBar_TabBar, "text": "Plot View", "type": "TabButton", "unnamed": 1, "visible": True}
easyDiffraction_Text_8 = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 35, "type": "Text", "unnamed": 1, "visible": True}
tabBar_Structure_View_TabButton = {"checkable": True, "container": tabBar_tabBar_TabBar, "text": "Structure View", "type": "TabButton", "unnamed": 1, "visible": True}
