app:
  name: easyDiffraction
  organization: easyDiffraction
  url: https://easydiffraction.org
structure:
  distribution: dist
  installer: dist
  configs: Configs
  scripts: Scripts
  certificates: Certificates
  examples: Examples
github:
  owner: easyDiffraction
  repo: easyDiffraction
pyinstaller:
  missing_libs:
    osx:
    - libshiboken2.abi3.*.dylib
    windows:
    - shiboken2.abi3.dll
    - MSVCP140.dll
    linux: []
release:
  version: 0.3.7
  date: 19 Nov 2019
  changes: # Get from pull requests description?
  - Minor Changes 1
  - Minor Changes 2
