# -*- coding: utf-8 -*-

import names

def main():
    startApplication("easyDiffraction")
    mouseClick(waitForObject(names.analysis_Button_2), 110, 26, Qt.LeftButton)    
    mouseClick(waitForObject(names.easyDiffraction_Open_another_project_Button), 129, 26, Qt.LeftButton)
    # Workaround for Windows not having the right winhook.dll
    snooze(5) 
    nativeType("full.rcif")
    snooze(1)
    nativeType("<Return>")
    snooze(1)
    # end of workaround        
    #mouseClick(waitForObject(names.label_MnemonicLabel))
    #mouseClick(waitForObject(names.easyDiffraction_Open_another_project_Button), 53, 27, Qt.LeftButton)
    mouseClick(waitForObject(names.easyDiffraction_Experimental_Data_Button), 359, 22, Qt.LeftButton)
    mouseClick(waitForObject(names.easyDiffraction_label_MnemonicLabel))
    test.compare(str(waitForObjectExists(names.easyDiffraction_chart_QtDataVisualization_DeclarativeScatter).id), "chart")
    test.compare(waitForObjectExists(names.easyDiffraction_chart_QtDataVisualization_DeclarativeScatter).enabled, True)
    test.compare(waitForObjectExists(names.easyDiffraction_chart_QtDataVisualization_DeclarativeScatter).visible, True)
    test.compare(waitForObjectExists(names.tabBar_Structure_View_TabButton).enabled, True)
    test.compare(waitForObjectExists(names.tabBar_Structure_View_TabButton).visible, True)
    test.compare(str(waitForObjectExists(names.tabBar_Structure_View_TabButton).text), "Structure View")
    test.compare(waitForObjectExists(names.tabBar_Text_View_CIF_TabButton).enabled, True)
    test.compare(str(waitForObjectExists(names.tabBar_Text_View_CIF_TabButton).text), "Text View (CIF)")
    test.compare(waitForObjectExists(names.tabBar_Text_View_CIF_TabButton).visible, True)
    test.compare(str(waitForObjectExists(names.easyDiffraction_Structural_phases_GroupBox).title), "Structural phases")
    test.compare(waitForObjectExists(names.easyDiffraction_Structural_phases_GroupBox).visible, True)
    test.compare(waitForObjectExists(names.easyDiffraction_Structural_phases_GroupBox).enabled, True)
    mouseClick(waitForObject(names.tabBar_Text_View_CIF_TabButton), 188, 19, Qt.LeftButton)
    test.compare(waitForObjectExists(names.textArea_TextArea).enabled, True)
    test.compare(waitForObjectExists(names.textArea_TextArea).lineCount, 87)
    test.compare(waitForObjectExists(names.textArea_TextArea).visible, True)
    mouseClick(waitForObject(names.tabbar_label_MnemonicLabel))
    test.compare(waitForObjectExists(names.easyDiffraction_View_settings_GroupBox).collapsed, True)
    mouseClick(waitForObject(names.tabbar_label_MnemonicLabel_2))
    test.compare(waitForObjectExists(names.easyDiffraction_Symmetry_and_cell_parameters_GroupBox).collapsed, True)
    test.compare(waitForObjectExists(names.easyDiffraction_Atoms_atomic_coordinates_and_occupations_GroupBox).collapsed, True)
    test.compare(waitForObjectExists(names.easyDiffraction_Atoms_atomic_coordinates_and_occupations_GroupBox).enabled, True)
    test.compare(str(waitForObjectExists(names.easyDiffraction_Atoms_atomic_coordinates_and_occupations_GroupBox).title), "Atoms, atomic coordinates and occupations")
    test.compare(waitForObjectExists(names.easyDiffraction_Atomic_displacement_parameters_10_GroupBox).collapsed, True)
    test.compare(waitForObjectExists(names.easyDiffraction_Atomic_displacement_parameters_10_GroupBox).enabled, True)
    test.compare(str(waitForObjectExists(names.easyDiffraction_Atomic_displacement_parameters_10_GroupBox).title), "Atomic displacement parameters ( × 10⁵ )")
    test.compare(waitForObjectExists(names.easyDiffraction_Magnetic_susceptibility_parameters_GroupBox).collapsed, True)
    test.compare(waitForObjectExists(names.easyDiffraction_Magnetic_susceptibility_parameters_GroupBox).enabled, True)
    test.compare(str(waitForObjectExists(names.easyDiffraction_Magnetic_susceptibility_parameters_GroupBox).title), "Magnetic susceptibility parameters")
    test.compare(waitForObjectExists(names.easyDiffraction_Analysis_Button).enabled, True)
    test.compare(str(waitForObjectExists(names.easyDiffraction_Analysis_Button).text), "Analysis")
    test.compare(waitForObjectExists(names.easyDiffraction_Experimental_Data_Button).enabled, True)
    test.compare(str(waitForObjectExists(names.easyDiffraction_Experimental_Data_Button).text), "Experimental Data")
