# encoding: UTF-8

from objectmaphelper import *

easyDiffraction_QQuickApplicationWindow = {"title": "easyDiffraction", "type": "QQuickApplicationWindow", "unnamed": 1, "visible": True}
easyDiffraction_Overlay = {"container": easyDiffraction_QQuickApplicationWindow, "type": "Overlay", "unnamed": 1, "visible": True}
label_MnemonicLabel = {"container": easyDiffraction_Overlay, "objectName": "label", "occurrence": 2, "type": "MnemonicLabel", "visible": True}
easyDiffraction_No_Project_Created_Opened_Text = {"container": easyDiffraction_QQuickApplicationWindow, "text": "No Project Created/Opened", "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_Text = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 2, "type": "Text", "unnamed": 1, "visible": True}
label_MnemonicLabel_2 = {"container": easyDiffraction_Overlay, "objectName": "label", "occurrence": 3, "type": "MnemonicLabel", "visible": True}
o_Rectangle = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "id": "titleArea", "text": "Program Preferences", "type": "Button", "unnamed": 1, "visible": True}
analysis_Button = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "id": "titleArea", "text": "Program Preferences", "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_image_IconImage = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "image", "occurrence": 3, "source": "file::/Imports/easyAnalysis/Resources/Icons/triangle-right.svg", "type": "IconImage", "visible": True}
easyDiffraction_Show_Animated_Intro_CheckBox = {"checkable": True, "container": easyDiffraction_QQuickApplicationWindow, "text": "Show Animated Intro", "type": "CheckBox", "unnamed": 1, "visible": True}
easyDiffraction_Show_User_Guides_CheckBox = {"checkable": True, "container": easyDiffraction_QQuickApplicationWindow, "text": "Show User Guides", "type": "CheckBox", "unnamed": 1, "visible": True}
easyDiffraction_Examples_Button = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "id": "titleArea", "text": "Examples", "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_Recent_Projects_Button = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "id": "titleArea", "text": "Recent Projects", "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_Experimental_Data_Button = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "text": "Experimental Data", "type": "Button", "unnamed": 1, "visible": True}
analysis_Button_2 = {"checkable": True, "container": easyDiffraction_Overlay, "id": "analysisButton", "text": "Analysis", "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_Open_another_project_Button = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "text": "Open another project", "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_Fe3O4_Text = {"container": easyDiffraction_QQuickApplicationWindow, "text": "Fe3O4", "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_Image = {"container": easyDiffraction_QQuickApplicationWindow, "source": "file:///C:/cygwin/home/piotrrozyczko/projects/easyDiffraction/Examples/Fe3O4_0T_powder_1d/structure.png", "type": "Image", "unnamed": 1, "visible": True}
easyDiffraction_Text_2 = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 16, "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_tabBar_TabBar = {"container": easyDiffraction_QQuickApplicationWindow, "id": "tabBar", "occurrence": 2, "type": "TabBar", "unnamed": 1, "visible": True}
tabBar_tabBar_TabBar = {"container": easyDiffraction_tabBar_TabBar, "id": "tabBar", "type": "TabBar", "unnamed": 1, "visible": True}
tabBar_Table_View_TabButton = {"checkable": True, "container": tabBar_tabBar_TabBar, "text": "Table View", "type": "TabButton", "unnamed": 1, "visible": True}
easyDiffraction_tabBar_TabBar_2 = {"container": easyDiffraction_QQuickApplicationWindow, "id": "tabBar", "type": "TabBar", "unnamed": 1, "visible": True}
tabBar_Experimental_Data_Button = {"checkable": True, "container": easyDiffraction_tabBar_TabBar_2, "text": "Experimental Data", "type": "Button", "unnamed": 1, "visible": True}
tabBar_label_MnemonicLabel = {"container": tabBar_tabBar_TabBar, "objectName": "label", "occurrence": 3, "type": "MnemonicLabel", "visible": True}
easyDiffraction_ScrollView = {"container": easyDiffraction_QQuickApplicationWindow, "type": "ScrollView", "unnamed": 1, "visible": True}
textArea_TextArea = {"container": easyDiffraction_ScrollView, "id": "textArea", "type": "TextArea", "unnamed": 1, "visible": True}
tabBar_Plot_View_TabButton = {"checkable": True, "container": tabBar_tabBar_TabBar, "text": "Plot View", "type": "TabButton", "unnamed": 1, "visible": True}
easyDiffraction_topChart_QtCharts_DeclarativeChart = {"container": easyDiffraction_QQuickApplicationWindow, "id": "topChart", "type": "QtCharts::DeclarativeChart", "unnamed": 1, "visible": True}
easyDiffraction_Sample_Model_Button = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "text": "Sample Model", "type": "Button", "unnamed": 1, "visible": True}
tabBar_label_MnemonicLabel_2 = {"container": tabBar_tabBar_TabBar, "objectName": "label", "occurrence": 2, "type": "MnemonicLabel", "visible": True}
easyDiffraction_ParametersTable = {"container": easyDiffraction_QQuickApplicationWindow, "type": "ParametersTable", "unnamed": 1, "visible": True}
o_Rectangle_2 = {"container": easyDiffraction_ParametersTable, "occurrence": 385, "type": "Rectangle", "unnamed": 1, "visible": True}
easyDiffraction_label_MnemonicLabel = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "label", "occurrence": 20, "type": "MnemonicLabel", "visible": True}
easyDiffraction_chart_QtDataVisualization_DeclarativeScatter = {"container": easyDiffraction_QQuickApplicationWindow, "id": "chart", "type": "QtDataVisualization::DeclarativeScatter", "unnamed": 1, "visible": True}
tabBar_Structure_View_TabButton = {"checkable": True, "container": tabBar_tabBar_TabBar, "text": "Structure View", "type": "TabButton", "unnamed": 1, "visible": True}
tabBar_Text_View_CIF_TabButton = {"checkable": True, "container": tabBar_tabBar_TabBar, "text": "Text View (CIF)", "type": "TabButton", "unnamed": 1, "visible": True}
easyDiffraction_Structural_phases_GroupBox = {"container": easyDiffraction_QQuickApplicationWindow, "title": "Structural phases", "type": "GroupBox", "unnamed": 1, "visible": True}
easyDiffraction_tabbar_TabBar = {"container": easyDiffraction_QQuickApplicationWindow, "id": "tabbar", "type": "TabBar", "unnamed": 1, "visible": True}
tabbar_label_MnemonicLabel = {"container": easyDiffraction_tabbar_TabBar, "objectName": "label", "occurrence": 2, "type": "MnemonicLabel", "visible": True}
easyDiffraction_View_settings_GroupBox = {"container": easyDiffraction_QQuickApplicationWindow, "title": "View settings", "type": "GroupBox", "unnamed": 1, "visible": True}
tabbar_label_MnemonicLabel_2 = {"container": easyDiffraction_tabbar_TabBar, "objectName": "label", "type": "MnemonicLabel", "visible": True}
easyDiffraction_Symmetry_and_cell_parameters_GroupBox = {"container": easyDiffraction_QQuickApplicationWindow, "id": "group1", "title": "Symmetry and cell parameters", "type": "GroupBox", "unnamed": 1, "visible": True}
easyDiffraction_Atoms_atomic_coordinates_and_occupations_GroupBox = {"container": easyDiffraction_QQuickApplicationWindow, "title": "Atoms, atomic coordinates and occupations", "type": "GroupBox", "unnamed": 1, "visible": True}
easyDiffraction_Atomic_displacement_parameters_10_GroupBox = {"container": easyDiffraction_QQuickApplicationWindow, "title": "Atomic displacement parameters ( × 10⁵ )", "type": "GroupBox", "unnamed": 1, "visible": True}
easyDiffraction_Magnetic_susceptibility_parameters_GroupBox = {"container": easyDiffraction_QQuickApplicationWindow, "title": "Magnetic susceptibility parameters", "type": "GroupBox", "unnamed": 1, "visible": True}
easyDiffraction_Analysis_Button = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "text": "Analysis", "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_Text_3 = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 34, "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_Text_4 = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 48, "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_label_MnemonicLabel_2 = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "label", "occurrence": 12, "type": "MnemonicLabel", "visible": True}
tabBar_Analysis_Button = {"checkable": True, "container": easyDiffraction_tabBar_TabBar_2, "text": "Analysis", "type": "Button", "unnamed": 1, "visible": True}
o_Rectangle_3 = {"container": easyDiffraction_ParametersTable, "occurrence": 349, "type": "Rectangle", "unnamed": 1, "visible": True}
o_Rectangle_4 = {"container": easyDiffraction_ParametersTable, "occurrence": 97, "type": "Rectangle", "unnamed": 1, "visible": True}
easyDiffraction_Next_step_Summary_Button = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "text": "Next step: Summary", "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_image_IconImage_2 = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "image", "source": "file::/Imports/easyAnalysis/Resources/Fonts/Awesome/svgs/arrow-circle-right.svg", "type": "IconImage", "visible": True}
easyDiffraction_image_IconImage_3 = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "image", "source": "file::/Imports/easyAnalysis/Resources/Icons/triangle-right.svg", "type": "IconImage", "visible": True}
tabbar_Basic_controls_TabButton = {"checkable": True, "container": easyDiffraction_tabbar_TabBar, "text": "Basic controls", "type": "TabButton", "unnamed": 1, "visible": True}
o_Rectangle_5 = {"container": easyDiffraction_ParametersTable, "occurrence": 369, "type": "Rectangle", "unnamed": 1, "visible": True}
