name: easydiffraction
version: git
summary: 'easyDiffraction - modelling and analysis of neutron diffraction data.'
description: |
  easyDiffraction is a scientific software for modelling and analysis of the neutron diffraction data.
  http://easydiffraction.github.io/

grade: stable # devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core18

architectures:
  - build-on: amd64

plugs:
  home-read:
    interface: home
    read:
      all

apps:
    easydiffraction:
        command: python3 $SNAP/easyDiffraction.py
        plugs:
          - opengl
          - desktop
          - wayland
          - x11
          - home-read
        desktop: usr/share/applications/easyDiffraction.desktop

parts:
  copy-app-files:
    plugin: dump
    source: ./App

  copy-desktop-icon-files:
    plugin: dump
    source: snap/gui
    organize:
      easyDiffraction.png: usr/share/applications/easyDiffraction.png
      easyDiffraction.desktop: usr/share/applications/easyDiffraction.desktop

  easydiffraction:
    plugin: python
    python-version: python3
    source: ./App
    stage-packages:
      - libnss3
      - libxcomposite1
      - libxcursor1
      - libxtst6
      - libxrandr2
      - libasound2
      - libglu1-mesa
      - libgles2-mesa
      - fontconfig
      - libxkbcommon0
      - libxkbcommon-x11-0
      - libxi6
      - libegl1
      - shared-mime-info
      - libgdk-pixbuf2.0-0
      - locales-all
      - libxslt1.1
      - xfonts-base
      - xfonts-scalable
    requirements:
      - /root/project/requirements.txt

layout:
  /etc/fonts:
    bind: $SNAP/pyside/etc/fonts